# Nixpacks configuration for Django application
[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["./build.sh"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 60 ethicic.wsgi:application"

[variables]
PYTHONPATH = "/app"
DJANGO_SETTINGS_MODULE = "ethicic.settings"