#!/bin/bash

# GitHub Setup Instructions
echo "=== GitHub Repository Setup ==="
echo ""
echo "Since GitHub CLI is not installed, please follow these steps:"
echo ""
echo "1. Go to GitHub.com and create a new repository:"
echo "   - Repository name: ethicic-public"
echo "   - Description: Ethical Capital public website - Django/Wagtail CMS"
echo "   - Visibility: Public"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "   # Add GitHub remote (replace YOUR_USERNAME with your GitHub username)"
echo "   git remote add origin git@github.com:YOUR_USERNAME/ethicic-public.git"
echo ""
echo "   # Or if using HTTPS:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/ethicic-public.git"
echo ""
echo "   # Push to GitHub"
echo "   git push -u origin main"
echo ""
echo "3. For Kinsta deployment:"
echo "   - Connect your GitHub repository to Kinsta"
echo "   - Configure environment variables in Kinsta dashboard:"
echo "     * SECRET_KEY (generate a secure key)"
echo "     * DATABASE_URL (provided by Kinsta)"
echo "     * ALLOWED_HOSTS (your domain)"
echo "     * Email settings if needed"
echo ""
echo "Current git status:"
git status --short
echo ""
echo "Repository is ready to push!"