# Generated by Django 5.1.5 on 2025-07-02 22:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0004_add_missing_strategy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategypage",
            name="performance_disclaimer",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Past performance is not indicative of future results. Investment returns and principal value will fluctuate.</p>",
            ),
        ),
    ]
