# Generated by Django 4.2.16 on 2025-07-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0009_add_about_page_layout_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_image",
            field=models.URLField(
                blank=True,
                default="https://pub-324a685032214395a8bcad478c265d4b.r2.dev/headshot%20sketch_slim.png",
                help_text="URL to headshot image",
            ),
        ),
    ]
