# Generated by Django to remove WordPress-related fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_ultimate_public_site_migration'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL: Remove WordPress columns
            sql=[
                "ALTER TABLE public_site_blogpost DROP COLUMN IF EXISTS wordpress_id;",
                "ALTER TABLE public_site_blogpost DROP COLUMN IF EXISTS wordpress_post_type;",
                "ALTER TABLE public_site_blogpost DROP COLUMN IF EXISTS wordpress_slug;",
                "ALTER TABLE public_site_blogpost DROP COLUMN IF EXISTS wordpress_status;",
            ],
            # Reverse SQL: Re-add WordPress columns (in case rollback is needed)
            reverse_sql=[
                "ALTER TABLE public_site_blogpost ADD COLUMN wordpress_id INTEGER NULL;",
                "ALTER TABLE public_site_blogpost ADD COLUMN wordpress_post_type VARCHAR(50) NULL;",
                "ALTER TABLE public_site_blogpost ADD COLUMN wordpress_slug VARCHAR(200) NULL;",
                "ALTER TABLE public_site_blogpost ADD COLUMN wordpress_status VARCHAR(20) NULL;",
            ]
        ),
    ]
