# Generated by Django 5.0.6 on 2025-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_remove_wordpress_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='display_title',
            field=models.CharField(
                blank=True,
                help_text='Optional custom title to display on the page (if blank, uses the page title)',
                max_length=255
            ),
        ),
    ]
