# Generated by Django 5.1.5 on 2025-07-06 00:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0003_add_business_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletterpage",
            name="page_ptr",
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="bluesky_url",
            field=models.URLField(
                blank=True, default="https://bsky.app/profile/sloaneortel.bsky.social"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link",
            field=models.URLField(
                blank=True,
                default="https://tidycal.com/ecic",
                help_text="Calendar booking link",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link_text",
            field=models.CharField(
                blank=True,
                default="Schedule with Sloane",
                help_text="Text for calendar link",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_url",
            field=models.URLField(blank=True, default="https://tidycal.com/ecic"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="client_focus_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Spending time getting to know our clients, which I find profoundly grounding. Building portfolios that reflect their values while delivering strong financial outcomes.</p>",
                help_text="Client focus description for What I Do Now panel",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="current_role_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Chief Investment Officer at Ethical Capital, translating insights from clients, colleagues, and research into investment strategies that align with values.</p>",
                help_text="Current role description for What I Do Now panel",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link",
            field=models.EmailField(
                blank=True,
                default="hello@ethicic.com",
                help_text="Contact email address",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link_text",
            field=models.CharField(
                blank=True,
                default="Or try email",
                help_text="Text for email link",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default='<ul class="external-roles"><li><strong>Co-founder</strong> - Woodcache Public Benefit Corporation</li><li><strong>Board Member</strong> - Responsible Alpha</li><li><strong>Co-host</strong> - "Free Money with Sloane and Ashby" podcast</li></ul>',
                help_text="External roles and leadership content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_title",
            field=models.CharField(
                blank=True,
                default="External Roles & Leadership",
                help_text="Title for external roles section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_description",
            field=models.CharField(
                blank=True,
                default="The best place to start understanding my personal journey",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_title",
            field=models.CharField(
                blank=True, default="How I Became an Active Manager", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_url",
            field=models.CharField(
                blank=True,
                default="/blog/how-i-became-an-active-manager/",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_description",
            field=models.CharField(
                blank=True,
                default="Perspective for long-term investors",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_title",
            field=models.CharField(
                blank=True, default="What Would a Recession Mean?", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_url",
            field=models.CharField(
                blank=True,
                default="/blog/what-would-a-recession-actually-mean-for-long-term-investors/",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_description",
            field=models.CharField(
                blank=True,
                default="Personal impact of economic changes",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_title",
            field=models.CharField(
                blank=True, default="What Does Inflation Mean to You?", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_url",
            field=models.CharField(
                blank=True,
                default="/blog/what-does-inflation-mean-to-you/",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_description",
            field=models.CharField(
                blank=True, default="Setting realistic expectations", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_title",
            field=models.CharField(
                blank=True,
                default="What Should You Expect When You're Investing?",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_url",
            field=models.CharField(
                blank=True,
                default="/blog/what-should-you-expect-when-youre-investing/",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_alt_text",
            field=models.CharField(
                blank=True,
                default="Sloane Ortel, Chief Investment Officer & Founder",
                help_text="Alt text for headshot image",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_image",
            field=models.URLField(
                blank=True,
                default="https://pub-324a685032214395a8bcad478c265d4b.r2.dev/headshot%20sketch_slim.png",
                help_text="URL to headshot image",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="instagram_url",
            field=models.URLField(
                blank=True, default="https://instagram.com/sloaneortel"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="linkedin_url",
            field=models.URLField(
                blank=True, default="https://www.linkedin.com/in/srvo0/"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="name",
            field=models.CharField(
                blank=True,
                default="Sloane Ortel (she/her)",
                help_text="Name and pronouns",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>When not managing portfolios, Sloane skis in Utah and replaces lawn with wildlife-friendly perennials, reflecting her appreciation for both adventure and the natural world that ethical investing seeks to protect.</p>",
                help_text="Personal interests content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_title",
            field=models.CharField(
                blank=True,
                default="Personal Interests",
                help_text="Title for personal interests section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our process is oriented towards cumulative learning—understanding companies, the communities they serve, and the consequences of their activities.</p>",
                help_text="Philosophy description for What I Do Now panel",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote",
            field=wagtail.fields.RichTextField(
                blank=True,
                default='<p>"There is no checklist comprehensive enough to rely upon. You have to pay attention."</p>',
                help_text="Philosophy quote in the hero section",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link",
            field=models.CharField(
                blank=True,
                default="/blog/how-i-became-an-active-manager/",
                help_text="Link for the philosophy quote attribution (can be relative or absolute URL)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link_text",
            field=models.CharField(
                blank=True,
                default="How I Became an Active Manager →",
                help_text="Text for the philosophy quote link",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Sloane started working in investment management right after high school, gaining experience at a regional brokerage firm and a Bangalore-based family office. She joined CFA Institute staff while still in college and spent nearly a decade creating educational materials for investment professionals, developing deep expertise in investment analysis and ethical investing practices.</p><p>Now at the center of the Ethical Capital Investment Collaborative, she translates insights from clients, colleagues, and research into investment strategies, focusing on understanding companies, the communities they serve, and the consequences of their activities.</p>",
                help_text="Professional background content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_title",
            field=models.CharField(
                blank=True,
                default="Professional Background",
                help_text="Title for professional background section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_title",
            field=models.CharField(
                blank=True,
                default="Chief Investment Officer & Founder",
                help_text="Professional title",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="sec_info_url",
            field=models.URLField(
                blank=True,
                default="https://adviserinfo.sec.gov/individual/summary/5388169",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaker_bio_url",
            field=models.URLField(
                blank=True,
                default="https://pub-324a685032214395a8bcad478c265d4b.r2.dev/Sloane-Ortel-Speaker-Bio.pdf",
                help_text="URL to speaker bio PDF",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_contact_note",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p><em>Fair warning: my Achilles heel is email. If you need me, your best bet is to get on my calendar.</em></p>",
                help_text="Contact note for speaking section",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_cta_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>For speaking engagements and media inquiries:</p>",
                help_text="Call-to-action text for speaking section",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_topics",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<ul><li>Aligning money with values for novice investors</li><li>Modern sustainable investing strategies</li><li>Ethical screening and portfolio construction</li><li>Investment management best practices</li></ul>",
                help_text="Topics covered in speaking engagements",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default='<p>Sloane offers keynote addresses and panel discussions on topics including ethical investing, portfolio management, and sustainable finance. She has written a textbook on investment idea generation and writes extensively about sustainable investing and financial values. Her insights have been featured in <a href="/media/" class="garden-action secondary">numerous media outlets</a>.</p>',
                help_text="Speaking & writing content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_title",
            field=models.CharField(
                blank=True,
                default="Speaking & Writing",
                help_text="Title for speaking & writing section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="tiktok_url",
            field=models.URLField(
                blank=True, default="https://tiktok.com/@ethicalcapital"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="twitter_url",
            field=models.URLField(
                blank=True, default="https://twitter.com/sloaneortel"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<h4>Expertise in Niche and Ethical Investing</h4><p>Deep knowledge and specialized focus on sustainable and ethical investing. Our in-house ethical screening goes beyond standard third-party data, offering rigorous transparency that distinguishes us from conventional options.</p><h4>Rigorous Analytical Process</h4><p>Systematic approach to investment analysis with proprietary screening of thousands of companies using our 'Tick' rating system, ensuring strategies are both ethically aligned and financially sound.</p><h4>Effective Client Communication</h4><p>High closing rates with prospective clients through clear communication of complex financial concepts and personal engagement, helping manage the emotional aspects of investing.</p><h4>Operational Support</h4><p>Experience with platforms like Altruist and Schwab, streamlining account opening, transfers, and SMA implementation for busy advisers.</p><h4>Educational Partnership</h4><p>Trusted thought partner providing consulting, ad-hoc analysis, and insights to help you navigate challenging client scenarios and develop expertise in ethical investing.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_title",
            field=models.CharField(
                blank=True, default="Why Partner With Us", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Join leading investment advisers who trust our multi-faceted approach to help them serve a broader range of clients with complex needs and values more effectively.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_title",
            field=models.CharField(
                blank=True, default="Ready to Partner?", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>As investment advisers ourselves, we understand the challenges of serving clients who want their portfolios to align with their principles. We provide the specialized research, proven strategies, and easy access you need to deliver exceptional outcomes.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                default="Deep research expertise and proven strategies to help you serve clients with complex values and sophisticated needs",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_title",
            field=models.CharField(
                blank=True, default="Partner with Ethical Capital", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We provide investment advisers with specialized expertise in niche and ethical investing, rigorous analytical processes, effective client communication support, operational assistance, and educational resources to help you serve clients with complex needs and values.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_title",
            field=models.CharField(
                blank=True, default="Advisory Services", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Access our comprehensive platform for portfolio construction, compliance monitoring, and client reporting.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_title",
            field=models.CharField(
                blank=True, default="Technology Platform", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>I provide actionable research insights to help you make informed investment decisions that align with your values and financial goals.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Essential research findings and market insights for ethical investing.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_title",
            field=models.CharField(
                blank=True, default="Featured Research", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>In-depth research and analysis on ethical investing, portfolio construction, and sustainable finance strategies.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(blank=True, default="Sloane Ortel", max_length=100),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                default="hello@ec1c.com",
                help_text="Contact email for consultations",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_subtitle",
            field=models.TextField(
                default="Let's discuss how we can help align your investments with your values.",
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_title",
            field=models.CharField(
                default="Schedule a Consultation",
                help_text="Main headline",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="form_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Please provide as much detail as possible so we can assist you effectively.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Have a question? We're here to help. Send us a message and we'll get back to you soon.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="thank_you_message",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We've received your message and will respond within 1-2 business days.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="thank_you_title",
            field=models.CharField(blank=True, default="Thank You!", max_length=200),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="email",
            field=models.EmailField(
                blank=True, default="hello@ethicic.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Ready to transform your investment research and compliance workflow?</p>",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_note",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p><strong>Important:</strong> This is a high-level overview. The complete criteria, methodology, and specific examples are detailed in our GitHub repository.</p>",
                help_text="Note about exclusions",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_section_title",
            field=models.CharField(
                blank=True,
                default="Key Exclusion Categories",
                help_text="Title for exclusions section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="github_criteria_url",
            field=models.URLField(
                default="https://github.com/ethicalcapital/sage/blob/main/screening_policy.md",
                help_text="URL to GitHub screening policy",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_subtitle",
            field=models.TextField(
                default="Transparent, rigorous screening criteria that guide our investment decisions.",
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_title",
            field=models.CharField(
                default="Our Ethical Criteria",
                help_text="Main headline",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_benefits",
            field=models.TextField(
                blank=True,
                default="Full documentation of exclusion criteria\nRegular updates as our research evolves\nCommunity feedback and discussion\nVersion history and change tracking",
                help_text="Benefits of transparency, one per line",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our ethical screening criteria are publicly available on GitHub. This ensures complete transparency about what we exclude and why.</p>",
                help_text="Description of transparency approach",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_section_title",
            field=models.CharField(
                blank=True,
                default="Open Source Transparency",
                help_text="Title for transparency section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaentry",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our Investment Encyclopedia provides clear, accessible explanations of key investment terms and concepts. Whether you're new to investing or looking to expand your knowledge, this resource helps you understand the language of finance and ethical investing.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Comprehensive investment terminology and concepts explained in plain language.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="exclusioncategory",
            name="icon",
            field=models.CharField(
                default="🚫", help_text="Emoji icon for category", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_address",
            field=models.CharField(
                blank=True, default="90 N 400 E, Provo, UT, 84606", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="hello@ethicic.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="+1 347 625 9000", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our comprehensive FAQ section provides detailed answers to help you understand our investment approach, account management, and ethical screening process.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Find answers to frequently asked questions about Ethical Capital Investment Collaborative.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="meeting_link",
            field=models.URLField(blank=True, default="https://tidycal.com/ecic"),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Frequently asked questions about the Garden Platform.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_subtitle",
            field=models.TextField(
                default="Comprehensive guide to ethical investing principles and strategies.",
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_title",
            field=models.CharField(
                default="Investment Guide", help_text="Main headline", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="client_availability_text",
            field=models.CharField(
                blank=True, default="Limited quarterly openings", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We work with a select number of clients who share our commitment to ethical excellence.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_section_header",
            field=models.CharField(
                blank=True,
                default="BEGIN YOUR ETHICAL INVESTMENT JOURNEY",
                help_text="Section header for call to action",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_title",
            field=models.CharField(
                blank=True,
                default="Ready to align your wealth with your values?",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="disclaimer_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Investment advisory services offered through Ethical Capital Investment Management LLC, a Registered Investment Adviser. Past performance does not guarantee future results. All investments involve risk. Please see our ADV Part 2 for important disclosures.</p><p>*Based on our analysis of S&P 500 constituents, approximately 57% failed one or more of our exclusion criteria. This percentage varies as companies and our criteria evolve.</p>",
                help_text="Legal disclaimer and footnotes",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="excluded_percentage",
            field=models.CharField(
                blank=True,
                default="57%",
                help_text="Percentage of S&P 500 excluded",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We hand-screen thousands of companies, exclude 57% of the S&P 500*, and build high-conviction portfolios where ethics and excellence converge. Fully transparent. Radically different. Fiduciary always.</p>",
                help_text="Hero description text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_tagline",
            field=models.CharField(
                blank=True, default="We're not like other firms. Good.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Concentrated ethical portfolios for investors who refuse to compromise",
                help_text="Main homepage headline",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="minimum_investment_text",
            field=models.CharField(
                blank=True, default="Available upon request", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We view ethical screening not as a limitation, but a luxury. Eliminating low-quality companies upfront reveals something profound: the businesses that survive our scrutiny are those woven into the fabric of healthy social systems. They grow because communities need them to grow. They succeed through reciprocal value exchange, not extraction. This insight that ethics reveal quality creates portfolios radically different from the market at large.</p>",
                help_text="Investment philosophy description",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_highlight",
            field=models.CharField(
                blank=True,
                default="When ethics and excellence converge, sustainable investing outcomes follow.",
                help_text="Key philosophy statement",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_section_header",
            field=models.CharField(
                blank=True,
                default="OUR INVESTMENT PHILOSOPHY",
                help_text="Section header for investment philosophy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_title",
            field=models.CharField(
                blank=True, default="Ethics Reveal Quality", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_content",
            field=models.TextField(
                blank=True,
                default="Ethics is not static. As companies evolve and disappoint we adapt. Our screening is a living framework, refined through ongoing research and client dialogue.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_title",
            field=models.CharField(
                blank=True, default="Continuous Evolution", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_content",
            field=models.TextField(
                blank=True,
                default="We acknowledge uncertainty, learn from mistakes, and evolve our approach. Humility serves our clients better than false certainty.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_title",
            field=models.CharField(
                blank=True, default="Intellectual Honesty", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_content",
            field=models.TextField(
                blank=True,
                default="We invest in companies, not stories. Real businesses with proven models, sustainable advantages, and ethical operations.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_title",
            field=models.CharField(
                blank=True, default="Business-Focused Investing", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Sophisticated ethical investing requires both conviction and nuance. These principles shape how we serve investors who refuse to compromise.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_section_header",
            field=models.CharField(
                blank=True,
                default="PRINCIPLES THAT GUIDE OUR WORK",
                help_text="Section header for principles",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_content",
            field=models.TextField(
                blank=True,
                default="We combine analytical depth with personalized service. Every holding is hand-researched, every client relationship carefully tended.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_title",
            field=models.CharField(
                blank=True,
                default="Institutional Rigor, Boutique Attention",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_content",
            field=models.TextField(
                blank=True,
                default="Our exclusion criteria are open source. Our process is documented. Our reasoning is clear. You deserve to understand exactly what you own and why.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_title",
            field=models.CharField(
                blank=True, default="Radical Transparency", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_content",
            field=models.TextField(
                blank=True,
                default="We maintain focused portfolios of 15-25 companies. Depth of research over breadth of holdings.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_title",
            field=models.CharField(
                blank=True, default="High-Conviction Concentration", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_section_header",
            field=models.CharField(
                blank=True,
                default="OUR SIGNATURE PROCESS",
                help_text="Section header for process",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_content",
            field=models.TextField(
                blank=True,
                default="We begin where others end. Our multi-factor screening excludes companies involved in fossil fuels, weapons, tobacco, human rights violations, and those failing our governance standards. This is not performative it is foundational.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_title",
            field=models.CharField(
                blank=True, default="Comprehensive Ethical Screening", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_content",
            field=models.TextField(
                blank=True,
                default="Beyond exclusions, we seek quality. Every company is evaluated through six lenses: People, Product, Execution, Valuation, Moat, and Risk. We combine traditional analysis with proprietary research tools to identify companies worthy of inclusion.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_title",
            field=models.CharField(
                blank=True, default="Fundamental Analysis", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_content",
            field=models.TextField(
                blank=True,
                default="From thousands screened to dozens analyzed to 15-25 owned. Each position is sized based on conviction, quality, and risk contribution. The result: high-conviction portfolios you can understand completely.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_title",
            field=models.CharField(
                blank=True, default="Portfolio Construction", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_content",
            field=models.TextField(
                blank=True,
                default="Markets change. Companies evolve. Values clarify. We monitor holdings continuously, engage with clients regularly, and adapt portfolios thoughtfully. Your investments should always align with both your values and your circumstances.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_title",
            field=models.CharField(
                blank=True,
                default="Continuous Monitoring and Evolution",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_title",
            field=models.CharField(
                blank=True, default="How We Build Ethical Portfolios", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_content",
            field=models.TextField(
                blank=True,
                default="RIAs and wealth managers looking for high-conviction ethical investment strategies for their clients.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_title",
            field=models.CharField(
                blank=True, default="Financial Advisers", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_content",
            field=models.TextField(
                blank=True,
                default="Investors seeking genuine ethical alignment with professional portfolio management and sustainable investing outcomes.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_title",
            field=models.CharField(
                blank=True, default="Individuals and Families", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_content",
            field=models.TextField(
                blank=True,
                default="Endowments, foundations, and family offices requiring documented ethical frameworks and fiduciary implementation.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_title",
            field=models.CharField(
                blank=True, default="Institutions and Foundations", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_section_header",
            field=models.CharField(
                blank=True,
                default="WHO WE SERVE",
                help_text="Section header for who we serve",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="since_year",
            field=models.CharField(
                blank=True,
                default="SINCE 2021",
                help_text="Year established or founding info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Each strategy offers a different approach to ethical investing, with varying levels of diversification and implementation.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_section_header",
            field=models.CharField(
                blank=True,
                default="THREE CORE STRATEGIES—MULTIPLE PATHS FORWARD",
                help_text="Section header for strategies",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="capabilities_title",
            field=models.CharField(
                blank=True, default="Our Capabilities", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Contact us to explore how we can support your institutional investment objectives.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_title",
            field=models.CharField(
                blank=True, default="Discuss Your Needs", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Custom investment strategies and compliance solutions designed for institutional scale and requirements.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                default="Scalable ethical investment solutions for institutions, endowments, and pension funds",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_title",
            field=models.CharField(
                blank=True, default="Institutional Investment Solutions", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our technology platform scales to handle institutional portfolio sizes and complexity.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_title",
            field=models.CharField(
                blank=True, default="Institutional Scale", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We work with institutions to implement ethical investment strategies at scale.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_title",
            field=models.CharField(
                blank=True, default="Institutional Solutions", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Media coverage, press releases, and company news.</p>",
                help_text="Introduction text that appears at the top of the media page",
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="press_kit_title",
            field=models.CharField(
                blank=True,
                default="Press Kit",
                help_text="Title for the press kit section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="form_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>This comprehensive form helps us understand your investment goals, risk tolerance, and ethical priorities to create your personalized portfolio strategy.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Take your first step toward ethical investing or jump in with both feet. Let's find the perfect mix of strategies for your values and needs.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_message",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We've received your information and will be in touch within 1-2 business days to discuss your personalized investment strategy.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_title",
            field=models.CharField(blank=True, default="Thank You!", max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="contact_cta",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Ready to discuss pricing for your practice? <a href='/contact/'>Contact our team</a> for a personalized quote.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="enterprise_title",
            field=models.CharField(
                blank=True, default="Enterprise Solutions", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Transparent pricing designed to scale with your practice.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="executive_summary",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Ethical Capital Investment Management is a registered investment adviser specializing in values-based equity investing. We integrate comprehensive ESG criteria throughout our investment process, excluding 57% of the S&P 500 through our proprietary screening methodology.</p>",
                help_text="Executive summary of ESG approach",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="form_adv_url",
            field=models.URLField(
                blank=True,
                default="https://reports.adviserinfo.sec.gov/reports/ADV/316032/PDF/316032.pdf",
                help_text="URL to Form ADV disclosure",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>As a signatory-aligned investment manager, we provide detailed responses to standard PRI due diligence questions covering our ESG integration, stewardship practices, and responsible investment approach.</p>",
                help_text="Hero section description",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_subtitle",
            field=models.TextField(
                default="Comprehensive responses to Principles for Responsible Investment due diligence questions.",
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_title",
            field=models.CharField(
                default="PRI Due Diligence Questionnaire",
                help_text="Main headline",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="screening_policy_url",
            field=models.URLField(
                default="https://github.com/ethicalcapital/sage/blob/main/screening_policy.md",
                help_text="URL to open-source screening policy",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="updated_at",
            field=models.CharField(
                default="January 2025",
                help_text="Month and year when this document was last updated",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Learn about our mission to democratize investment intelligence and compliance technology.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="process_overview",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our investment process combines ethical screening with disciplined portfolio construction.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We built the best ethical framework we could—then kept building. Our criteria evolve in response to whatever harmful patterns emerge in the world, adapting as we learn more about both harm and healing. We seek companies making unmistakable positive contributions to all inhabitants—human and non-human animals alike.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_title",
            field=models.CharField(
                blank=True, default="A Living Framework", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>From the remaining ethical universe, we identify companies with strong fundamentals, competitive advantages, and reasonable valuations. We look for businesses we understand, with management teams we trust, trading at prices that make sense.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_title",
            field=models.CharField(
                blank=True, default="Quality & Value Analysis", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We build diversified portfolios that balance risk, return, and ethical impact. Our three core strategies can be mixed and matched to create the perfect allocation for your values, risk tolerance, and income needs.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_title",
            field=models.CharField(
                blank=True, default="Portfolio Construction", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We continuously monitor holdings for changes in business practices, financial health, and market conditions. If a company no longer meets our criteria, we remove it from the portfolio.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_title",
            field=models.CharField(
                blank=True, default="Ongoing Monitoring", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>I provide actionable research insights to help you make informed investment decisions that align with your values and financial goals.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Essential research findings and market insights for ethical investing.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_title",
            field=models.CharField(
                blank=True, default="Featured Research", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>In-depth research and analysis on ethical investing, portfolio construction, and sustainable finance strategies.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="accessibility_phone",
            field=models.CharField(
                default="+1 (801) 123-4567",
                help_text="Accessibility support phone number",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="business_hours",
            field=models.CharField(
                default="Monday - Friday, 9:00 AM - 5:00 PM MT",
                help_text="Business hours display text",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="cio_email",
            field=models.EmailField(
                default="sloane@ethicic.com",
                help_text="Chief Investment Officer email",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="city",
            field=models.CharField(default="Provo", help_text="City", max_length=100),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company_description",
            field=models.TextField(
                default="Utah-registered investment advisor specializing in ethical portfolio management and concentrated sustainable investing strategies.",
                help_text="Company description for meta tags and schema markup",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company_name",
            field=models.CharField(
                default="Ethical Capital",
                help_text="Company brand name displayed in navigation and footer",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company_tagline",
            field=models.CharField(
                default="Institutional-Grade Ethical Investing",
                help_text="Main tagline for SEO and social media",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_error_message",
            field=models.TextField(
                default="Please correct the errors below and try again.",
                help_text="Error message for contact form submissions",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_success_message",
            field=models.TextField(
                default="Thank you for your message! We will get back to you within 24 hours.",
                help_text="Success message for contact form submissions",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="copyright_text",
            field=models.CharField(
                default="Ethical Capital Investment Collaborative. All rights reserved.",
                help_text="Footer copyright text",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="country",
            field=models.CharField(
                default="United States", help_text="Country", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="default_meta_description",
            field=models.TextField(
                default="Ethical Capital - Institutional-Grade Ethical Investing",
                help_text="Default meta description for pages without custom descriptions",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="founding_year",
            field=models.CharField(
                default="2021", help_text="Company founding year", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_balanced_desc",
            field=models.TextField(
                default="Mix of growth and income, moderate risk tolerance",
                help_text="Balanced investment goal description",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_balanced_title",
            field=models.CharField(
                default="Balanced Approach",
                help_text="Balanced investment goal title",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_growth_desc",
            field=models.TextField(
                default="Building wealth over time, comfortable with market volatility",
                help_text="Growth investment goal description",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_growth_title",
            field=models.CharField(
                default="Long-term Growth",
                help_text="Growth investment goal title",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_income_desc",
            field=models.TextField(
                default="Regular income from investments, with some growth potential",
                help_text="Income investment goal description",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_income_title",
            field=models.CharField(
                default="Current Income",
                help_text="Income investment goal title",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_preservation_desc",
            field=models.TextField(
                default="Protecting principal, minimal risk, steady returns",
                help_text="Preservation investment goal description",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_preservation_title",
            field=models.CharField(
                default="Capital Preservation",
                help_text="Preservation investment goal title",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="meta_keywords",
            field=models.CharField(
                default="investment intelligence, compliance, portfolio management, financial advisory",
                help_text="Default meta keywords",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="minimum_investment",
            field=models.CharField(
                default="$25,000", help_text="Minimum investment amount", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_description",
            field=models.TextField(
                default="Get our latest insights on ethical investing delivered to your inbox.",
                help_text="Newsletter signup description",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_privacy_text",
            field=models.CharField(
                default="We respect your privacy. Unsubscribe at any time.",
                help_text="Newsletter privacy notice",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_success_message",
            field=models.TextField(
                default="Thank you for subscribing to our newsletter!",
                help_text="Success message for newsletter subscriptions",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_title",
            field=models.CharField(
                default="Stay Updated",
                help_text="Newsletter signup widget title",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="postal_code",
            field=models.CharField(
                default="84606", help_text="Postal/ZIP code", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_email",
            field=models.EmailField(
                default="hello@ethicic.com",
                help_text="Primary contact email address",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_phone",
            field=models.CharField(
                default="+1 347 625 9000",
                help_text="Primary phone number",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="state",
            field=models.CharField(
                default="UT", help_text="State or region", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="street_address",
            field=models.CharField(
                default="90 N 400 E", help_text="Street address", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="support_email",
            field=models.EmailField(
                default="hello@ethicic.com",
                help_text="Support and accessibility contact email",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="twitter_handle",
            field=models.CharField(
                default="@ethicalcapital",
                help_text="Twitter handle (include @)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="advisors_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Partner with us to serve clients who want their portfolios to align with their principles. We provide the specialized research, proven strategies, and operational support you need.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="advisors_title",
            field=models.CharField(
                blank=True, default="For Investment Advisers", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Let's find the perfect solution for your needs. Contact us to discuss how we can help you achieve your investment goals while staying true to your values.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="cta_title",
            field=models.CharField(
                blank=True, default="Ready to Get Started?", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Whether you're an individual investor, institutional client, or investment adviser, we provide sophisticated ethical investment solutions that align your portfolio with your principles.</p>",
                help_text="Hero section description",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_subtitle",
            field=models.TextField(
                default="Ethical investment strategies tailored for individuals, institutions, and investment advisers.",
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_title",
            field=models.CharField(
                default="Investment Solutions",
                help_text="Main headline",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="individuals_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Take your first step toward ethical investing or jump in with both feet. Our personalized approach helps you align your investments with your values while achieving your financial goals.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="individuals_title",
            field=models.CharField(
                blank=True, default="For Individuals", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="institutions_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Scalable ethical investment solutions for endowments, pension funds, and institutional clients who require sophisticated strategies at institutional scale.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="institutions_title",
            field=models.CharField(
                blank=True, default="For Institutions", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="strategies_intro",
            field=models.TextField(
                blank=True,
                default="Our investment solutions are built around three core strategies, tailored to three distinct audiences, and delivered through multiple channels to meet you where you are.",
                help_text="Introduction text for strategies section",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="strategies_section_title",
            field=models.CharField(
                blank=True,
                default="Three Strategies, Infinite Possibilities",
                help_text="Title for strategies section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="strategycard",
            name="icon",
            field=models.CharField(
                default="🚀", help_text="Emoji icon for strategy", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="strategydocument",
            name="icon",
            field=models.CharField(
                default="📄", help_text="Emoji icon for document", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Compare our investment strategies to find the approach that best matches your goals and risk tolerance.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_title",
            field=models.CharField(
                blank=True, default="Strategy Comparison", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Each strategy follows our rigorous ethical screening process and disciplined investment approach to help you achieve your financial goals.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our investment strategies are designed to align your portfolio with your values while delivering strong financial performance.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="benchmark_name",
            field=models.CharField(
                blank=True,
                default="ACWI",
                help_text="e.g., ACWI, AGG/PFF, S&P 500",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="best_for",
            field=models.CharField(
                blank=True, default="Long-term growth", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="cash_allocation",
            field=models.CharField(blank=True, default="0.93%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="commentary_title",
            field=models.CharField(
                blank=True, default="Strategy Commentary", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="documents_title",
            field=models.CharField(
                blank=True, default="Strategy Documents", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ethical_implementation",
            field=models.CharField(
                blank=True, default="100% Full Criteria", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="exclusions_note",
            field=models.CharField(
                blank=True, default="22% of benchmark index excluded", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="healthcare_exclusion_note",
            field=models.TextField(
                blank=True,
                default="* Healthcare exclusions are selective, focused on companies that directly support abortion procedures or controversial research practices",
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="holdings_count",
            field=models.CharField(blank=True, default="15-25", max_length=50),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_benchmark",
            field=models.CharField(blank=True, default="12.3%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_difference",
            field=models.CharField(blank=True, default="+3.4%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_return",
            field=models.CharField(blank=True, default="15.7%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="overweights_note",
            field=models.CharField(
                blank=True, default="Higher conviction in these sectors", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="performance_disclaimer",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Past performance is not indicative of future results. Investment returns and principal value will fluctuate.</p>",
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="process_title",
            field=models.CharField(blank=True, default="Our Process", max_length=200),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="risk_level",
            field=models.CharField(
                blank=True, default="Full market exposure", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_benchmark",
            field=models.CharField(blank=True, default="9.5%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_difference",
            field=models.CharField(blank=True, default="+2.6%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_return",
            field=models.CharField(blank=True, default="12.1%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_benchmark",
            field=models.CharField(blank=True, default="7.2%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_difference",
            field=models.CharField(blank=True, default="+2.6%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_return",
            field=models.CharField(blank=True, default="9.8%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_benchmark",
            field=models.CharField(blank=True, default="5.1%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_difference",
            field=models.CharField(blank=True, default="+3.1%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_return",
            field=models.CharField(blank=True, default="8.2%", max_length=20),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("contact", "Contact Form"),
                    ("newsletter", "Newsletter Signup"),
                    ("onboarding", "Onboarding Request"),
                    ("garden_interest", "Garden Platform Interest"),
                ],
                default="contact",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="AccessibilityPage",
        ),
        migrations.DeleteModel(
            name="NewsletterPage",
        ),
    ]
