# Generated by Django 5.1.5 on 2025-07-06 23:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0004_remove_newsletterpage_page_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingpage",
            name="additional_services",
            field=wagtail.fields.StreamField(
                [("service", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    1: ("wagtail.blocks.TextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("fee_text", 2),
                                ("cta_text", 3),
                                ("cta_link", 0),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Discover how we combine rigorous analysis with ethical principles to build portfolios that reflect your values.</p>",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="cta_section_header",
            field=models.CharField(
                blank=True, default="LEARN MORE ABOUT US", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="cta_title",
            field=models.CharField(
                blank=True,
                default="Explore our approach to ethical investing",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="fee_calculation_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Fees are calculated quarterly based on average daily balance and debited directly from your account. No hidden costs or transaction fees.</p>",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="fee_calculation_title",
            field=models.CharField(
                blank=True, default="Fee Calculation", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_badge",
            field=models.CharField(
                blank=True, default="INDIVIDUAL INVESTORS", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_cta_link",
            field=models.CharField(
                blank=True, default="/consultation/", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_cta_text",
            field=models.CharField(
                blank=True, default="SCHEDULE CONSULTATION", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_features",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<ul>\n<li>Work directly with Ethical Capital</li>\n<li>Personalized portfolio management</li>\n<li>Real-time reporting through client portal</li>\n<li>Comprehensive reporting</li>\n</ul>",
                help_text="Features for individual pricing tier",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_price",
            field=models.CharField(blank=True, default="1.00%", max_length=20),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_price_period",
            field=models.CharField(blank=True, default="annually", max_length=50),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_subtitle",
            field=models.CharField(
                blank=True, default="For individuals and families", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="individual_title",
            field=models.CharField(
                blank=True, default="Direct Client Relationships", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="institutional_badge",
            field=models.CharField(
                blank=True, default="INSTITUTIONAL PRICING", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="institutional_features",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<ul>\n<li>Access through Schwab, Altruist, or your preferred custodian</li>\n<li>Direct access to CIO</li>\n<li>SMA implementation</li>\n<li>Quarterly performance reporting</li>\n</ul>",
                help_text="Features for institutional pricing tier",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="institutional_price",
            field=models.CharField(blank=True, default="0.50%", max_length=20),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="institutional_price_period",
            field=models.CharField(blank=True, default="annually", max_length=50),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="institutional_subtitle",
            field=models.CharField(
                blank=True,
                default="For RIAs, institutions, and platform clients",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="institutional_title",
            field=models.CharField(
                blank=True, default="Adviser & Platform Access", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="minimum_investment_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Direct management minimums vary by strategy. Schwab platform accounts follow standard SMA minimums. Contact us for current requirements.</p>",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="minimum_investment_title",
            field=models.CharField(
                blank=True, default="Minimum Investment", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="pricing_rationale_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Individual clients (1.00%) receive comprehensive personal service directly from us. Institutional clients (0.50%) access our strategies through their existing adviser relationships or platforms, reflecting economies of scale.</p>",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="pricing_rationale_title",
            field=models.CharField(
                blank=True, default="Why Different Pricing?", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="section_header",
            field=models.CharField(
                blank=True,
                default="TRANSPARENT PRICING FOR EVERY CLIENT TYPE",
                help_text="Main pricing section header",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="section_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Simple, transparent pricing based on how you access our services. Individual investors work directly with us at 1.00% annually. Institutional clients accessing through advisers or platforms pay 0.50% annually.</p>",
                help_text="Introduction text for pricing section",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="services_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Specialized services for institutional clients and platform partners.</p>",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="services_section_header",
            field=models.CharField(
                blank=True, default="ADDITIONAL SERVICES", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="show_workshop_form",
            field=models.BooleanField(
                default=True, help_text="Show the workshop request form"
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="workshop_form_title",
            field=models.CharField(
                blank=True, default="Request a Workshop or Presentation", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="workshop_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Professional presentations on ethical investing, sustainable finance, and values-aligned wealth management. Topics range from foundational concepts to advanced portfolio construction strategies.</p>",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="workshop_nonprofit_note",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p><strong>Note:</strong> We provide complimentary presentations to mission-aligned nonprofit organizations and advocacy groups.</p>",
            ),
        ),
        migrations.AddField(
            model_name="pricingpage",
            name="workshop_section_header",
            field=models.CharField(
                blank=True,
                default="EDUCATIONAL WORKSHOPS & SPEAKING ENGAGEMENTS",
                max_length=200,
            ),
        ),
    ]
