# Generated by Django 5.1.5 on 2025-06-30 08:42

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0004_fix_aboutpage_fields"),
        ("wagtailcore", "0095_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_section_header",
            field=models.CharField(
                blank=True,
                default="BEGIN YOUR ETHICAL INVESTMENT JOURNEY",
                help_text="Section header for call to action",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="philosophy_section_header",
            field=models.CharField(
                blank=True,
                default="OUR INVESTMENT PHILOSOPHY",
                help_text="Section header for investment philosophy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="principles_section_header",
            field=models.CharField(
                blank=True,
                default="PRINCIPLES THAT GUIDE OUR WORK",
                help_text="Section header for principles",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="process_section_header",
            field=models.CharField(
                blank=True,
                default="OUR SIGNATURE PROCESS",
                help_text="Section header for process",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="serve_section_header",
            field=models.CharField(
                blank=True,
                default="WHO WE SERVE",
                help_text="Section header for who we serve",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategies_section_header",
            field=models.CharField(
                blank=True,
                default="THREE CORE STRATEGIES—MULTIPLE PATHS FORWARD",
                help_text="Section header for strategies",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_image",
            field=models.URLField(
                blank=True,
                default="https://pub-324a685032214395a8bcad478c265d4b.r2.dev/headshot%20sketch_slim.png",
                help_text="URL to headshot image",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link",
            field=models.URLField(
                blank=True,
                default="/blog/how-i-became-an-active-manager/",
                help_text="Link for the philosophy quote attribution",
            ),
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Ethical Capital",
                        help_text="Company brand name displayed in navigation and footer",
                        max_length=100,
                    ),
                ),
                (
                    "company_tagline",
                    models.CharField(
                        default="Institutional-Grade Ethical Investing",
                        help_text="Main tagline for SEO and social media",
                        max_length=200,
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        default="SEC-registered investment advisor specializing in ethical portfolio management and concentrated sustainable investing strategies.",
                        help_text="Company description for meta tags and schema markup",
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        default="hello@ethicic.com",
                        help_text="Primary contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="hello@ethicic.com",
                        help_text="Support and accessibility contact email",
                        max_length=254,
                    ),
                ),
                (
                    "cio_email",
                    models.EmailField(
                        default="sloane@ethicic.com",
                        help_text="Chief Investment Officer email",
                        max_length=254,
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        default="+1 347 625 9000",
                        help_text="Primary phone number",
                        max_length=20,
                    ),
                ),
                (
                    "accessibility_phone",
                    models.CharField(
                        default="+1 (801) 123-4567",
                        help_text="Accessibility support phone number",
                        max_length=20,
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        default="90 N 400 E", help_text="Street address", max_length=200
                    ),
                ),
                (
                    "city",
                    models.CharField(default="Provo", help_text="City", max_length=100),
                ),
                (
                    "state",
                    models.CharField(
                        default="UT", help_text="State or region", max_length=50
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        default="84606", help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="United States", help_text="Country", max_length=100
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        default="@ethicalcapital",
                        help_text="Twitter handle (include @)",
                        max_length=50,
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn company page URL"),
                ),
                (
                    "default_meta_description",
                    models.TextField(
                        default="Ethical Capital - Institutional-Grade Ethical Investing",
                        help_text="Default meta description for pages without custom descriptions",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        default="investment intelligence, compliance, portfolio management, financial advisory",
                        help_text="Default meta keywords",
                        max_length=300,
                    ),
                ),
                (
                    "founding_year",
                    models.CharField(
                        default="2021", help_text="Company founding year", max_length=4
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="Ethical Capital Investment Collaborative. All rights reserved.",
                        help_text="Footer copyright text",
                        max_length=200,
                    ),
                ),
                (
                    "business_hours",
                    models.CharField(
                        default="Monday - Friday, 9:00 AM - 5:00 PM MT",
                        help_text="Business hours display text",
                        max_length=100,
                    ),
                ),
                (
                    "minimum_investment",
                    models.CharField(
                        default="$25,000",
                        help_text="Minimum investment amount",
                        max_length=20,
                    ),
                ),
                (
                    "contact_success_message",
                    models.TextField(
                        default="Thank you for your message! We will get back to you within 24 hours.",
                        help_text="Success message for contact form submissions",
                    ),
                ),
                (
                    "contact_error_message",
                    models.TextField(
                        default="Please correct the errors below and try again.",
                        help_text="Error message for contact form submissions",
                    ),
                ),
                (
                    "newsletter_success_message",
                    models.TextField(
                        default="Thank you for subscribing to our newsletter!",
                        help_text="Success message for newsletter subscriptions",
                    ),
                ),
                (
                    "newsletter_title",
                    models.CharField(
                        default="Stay Updated",
                        help_text="Newsletter signup widget title",
                        max_length=100,
                    ),
                ),
                (
                    "newsletter_description",
                    models.TextField(
                        default="Get our latest insights on ethical investing delivered to your inbox.",
                        help_text="Newsletter signup description",
                    ),
                ),
                (
                    "newsletter_privacy_text",
                    models.CharField(
                        default="We respect your privacy. Unsubscribe at any time.",
                        help_text="Newsletter privacy notice",
                        max_length=200,
                    ),
                ),
                (
                    "investment_goal_growth_title",
                    models.CharField(
                        default="Long-term Growth",
                        help_text="Growth investment goal title",
                        max_length=50,
                    ),
                ),
                (
                    "investment_goal_growth_desc",
                    models.TextField(
                        default="Building wealth over time, comfortable with market volatility",
                        help_text="Growth investment goal description",
                    ),
                ),
                (
                    "investment_goal_income_title",
                    models.CharField(
                        default="Current Income",
                        help_text="Income investment goal title",
                        max_length=50,
                    ),
                ),
                (
                    "investment_goal_income_desc",
                    models.TextField(
                        default="Regular income from investments, with some growth potential",
                        help_text="Income investment goal description",
                    ),
                ),
                (
                    "investment_goal_balanced_title",
                    models.CharField(
                        default="Balanced Approach",
                        help_text="Balanced investment goal title",
                        max_length=50,
                    ),
                ),
                (
                    "investment_goal_balanced_desc",
                    models.TextField(
                        default="Mix of growth and income, moderate risk tolerance",
                        help_text="Balanced investment goal description",
                    ),
                ),
                (
                    "investment_goal_preservation_title",
                    models.CharField(
                        default="Capital Preservation",
                        help_text="Preservation investment goal title",
                        max_length=50,
                    ),
                ),
                (
                    "investment_goal_preservation_desc",
                    models.TextField(
                        default="Protecting principal, minimal risk, steady returns",
                        help_text="Preservation investment goal description",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="NavigationMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Text displayed in navigation", max_length=50
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL or path (e.g., /about/, /process/)",
                        max_length=200,
                    ),
                ),
                (
                    "external",
                    models.BooleanField(
                        default=False, help_text="Open in new tab/window"
                    ),
                ),
                (
                    "show_in_nav",
                    models.BooleanField(
                        default=True,
                        help_text="Display this item in the main navigation",
                    ),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=True, help_text="Display this item in the footer"
                    ),
                ),
                (
                    "parent",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_items",
                        to="public_site.siteconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Menu Item",
            },
        ),
    ]
