# Generated by Django 5.1.5 on 2025-07-06 23:06

from django.db import migrations
import json


def populate_additional_services(apps, schema_editor):
    PricingPage = apps.get_model("public_site", "PricingPage")

    default_services = [
        {
            "type": "service",
            "value": {
                "title": "Institutional Consulting",
                "description": "Sub-advisory services for RIAs, family offices, and institutions seeking ethical investment expertise.",
                "fee_text": "Custom fee arrangements",
                "cta_text": "LEARN MORE",
                "cta_link": "/institutions/",
            },
        },
        {
            "type": "service",
            "value": {
                "title": "Garden Platform Access",
                "description": "Our proprietary research and portfolio management platform for qualified financial professionals.",
                "fee_text": "Alpha access - contact for details",
                "cta_text": "EXPLORE GARDEN",
                "cta_link": "/garden/",
            },
        },
    ]

    for page in PricingPage.objects.all():
        if not page.additional_services:
            page.additional_services = json.dumps(default_services)
            page.save()


def reverse_populate_additional_services(apps, schema_editor):
    # No need to reverse - just leave the field empty
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0005_add_comprehensive_pricing_fields"),
    ]

    operations = [
        migrations.RunPython(
            populate_additional_services, reverse_populate_additional_services
        ),
    ]
