# Generated by Django 5.1.5 on 2025-07-06 23:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0006_populate_pricing_additional_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="processpage",
            name="conduct_exclusions",
            field=wagtail.fields.StreamField(
                [("exclusion_category", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.ListBlock", (1,), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="conduct_exclusions_subtitle",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Even companies making beneficial products can cause harm through their conduct. We track patterns of behavior that damage communities, workers, and ecosystems.</p>",
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="conduct_exclusions_title",
            field=models.CharField(
                blank=True, default="CONDUCT-BASED EXCLUSIONS", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Schedule a consultation to discuss how our process can work for your unique situation.</p>",
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="cta_title",
            field=models.CharField(
                blank=True, default="Ready to invest with intention?", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="exclusion_date",
            field=models.CharField(
                blank=True,
                default="as of June 14, 2025",
                help_text="Date of exclusion percentage calculation",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="exclusion_percentage",
            field=models.CharField(
                blank=True,
                default="57%",
                help_text="Percentage of S&P 500 excluded",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="methodology_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default='<p>Our criteria are meant to avoid involvement with all preventable harms we are aware of. This excludes 57% of the S&P 500 (as of June 14, 2025). Our complete methodology is <a href="https://github.com/ethicalcapital/sage/blob/main/screening_policy.md" target="_blank" rel="noopener noreferrer" class="policy-link">open source on GitHub</a> under an MIT license.</p>',
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="methodology_title",
            field=models.CharField(
                blank=True, default="Do Our Best, Then Do Better", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="principles_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Throughout our process, we're guided by simple principles: ethics reveal quality, transparency builds trust, and sustainable investing means considering all stakeholders.</p>",
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="principles_title",
            field=models.CharField(
                blank=True, default="GUIDING PRINCIPLES", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="product_exclusions",
            field=wagtail.fields.StreamField(
                [("exclusion_category", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.ListBlock", (1,), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="product_exclusions_subtitle",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We exclude companies whose business models depend on creating products that harm living beings.</p>",
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="product_exclusions_title",
            field=models.CharField(
                blank=True, default="PRODUCT-BASED EXCLUSIONS", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="screening_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We begin with rigorous screening that excludes companies involved in preventable harms. Our criteria cover both product-based exclusions (animal products, weapons, fossil fuels, addiction, surveillance) and conduct-based exclusions (human rights violations, environmental damage, corporate misconduct). This comprehensive approach ensures your investments align with your values.</p>",
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="screening_title",
            field=models.CharField(
                blank=True, default="Ethical Screening & Exclusions", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="processpage",
            name="section_header",
            field=models.CharField(
                blank=True, default="OUR SIGNATURE PROCESS", max_length=200
            ),
        ),
    ]
