# Generated by Django 5.1.5 on 2025-07-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0007_add_missing_document_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategydocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("performance", "Performance Reports"),
                    ("strategy", "Strategy Information"),
                    ("regulatory", "Regulatory Disclosures"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="strategydocument",
            name="document_url",
            field=models.URLField(
                blank=True, help_text="Link to document if available"
            ),
        ),
        migrations.AlterField(
            model_name="strategydocument",
            name="icon",
            field=models.CharField(
                default="📄", help_text="Emoji icon for document", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="strategygeographicallocation",
            name="allocation_percent",
            field=models.CharField(help_text="e.g., 78.0%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategygeographicallocation",
            name="benchmark_percent",
            field=models.CharField(help_text="e.g., 62.0%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategygeographicallocation",
            name="difference_percent",
            field=models.CharField(help_text="e.g., +16.0%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategygeographicallocation",
            name="region",
            field=models.CharField(
                help_text="e.g., United States, International", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="strategyholding",
            name="key_metrics",
            field=models.TextField(
                help_text="e.g., 40%+ annual revenue growth, AI market leader"
            ),
        ),
        migrations.AlterField(
            model_name="strategyholding",
            name="ticker_symbol",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="strategyholding",
            name="vertical",
            field=models.CharField(
                help_text="e.g., Lending, Real Estate, Innovation", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="strategyholding",
            name="weight_percent",
            field=models.CharField(help_text="e.g., ~8.4%", max_length=20),
        ),
        migrations.AlterField(
            model_name="strategysectorposition",
            name="note",
            field=models.TextField(
                blank=True, help_text="Additional notes about this sector"
            ),
        ),
        migrations.AlterField(
            model_name="strategysectorposition",
            name="position_type",
            field=models.CharField(
                choices=[("overweight", "Overweight"), ("exclusion", "Exclusion")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="strategyverticalallocation",
            name="dividend_yield",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="strategyverticalallocation",
            name="fcf_market_cap",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="strategyverticalallocation",
            name="is_benchmark_row",
            field=models.BooleanField(
                default=False, help_text="Check for benchmark comparison row"
            ),
        ),
        migrations.AlterField(
            model_name="strategyverticalallocation",
            name="is_total_row",
            field=models.BooleanField(
                default=False, help_text="Check for portfolio total row"
            ),
        ),
        migrations.AlterField(
            model_name="strategyverticalallocation",
            name="pe_ratio",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="strategyverticalallocation",
            name="revenue_cagr",
            field=models.CharField(max_length=20),
        ),
    ]
