# Generated by Django 5.1.5 on 2025-07-06 23:52

from django.db import migrations


def populate_process_page_fields(apps, schema_editor):
    ProcessPage = apps.get_model("public_site", "ProcessPage")

    # Define product exclusions data
    product_exclusions = [
        {
            "type": "exclusion_category",
            "value": {
                "title": "Animal Products",
                "items": [
                    "→ Meat, dairy, eggs production",
                    "→ Leather, hide, fur, silk production",
                    "→ Fishing & hunting equipment",
                    "→ Factory farming operations",
                    "→ Animal testing for non-medical purposes",
                    "→ Entertainment using live animals",
                ],
            },
        },
        {
            "type": "exclusion_category",
            "value": {
                "title": "Weapons & Military",
                "items": [
                    "→ Weapons manufacturing",
                    "→ Military materiel & consulting",
                    "→ Defense contracting",
                    "→ Private military contractors",
                ],
            },
        },
        {
            "type": "exclusion_category",
            "value": {
                "title": "Fossil Fuels & Extraction",
                "items": [
                    "→ Fossil fuel extraction & refining",
                    "→ Thermal coal (≥30% revenue/operations)",
                    "→ Coal power (>10,000 MW capacity)",
                    "→ Extractive industries (>20M tonnes annually)",
                ],
            },
        },
        {
            "type": "exclusion_category",
            "value": {
                "title": "Addiction & Public Health",
                "items": [
                    "→ Tobacco products",
                    "→ Harmful chemicals & toxins",
                    "→ Addiction-enabling businesses",
                    "→ For-profit prison operations",
                ],
            },
        },
        {
            "type": "exclusion_category",
            "value": {
                "title": "Surveillance Technology",
                "items": [
                    "→ Privacy invasion for profit",
                    "→ Data exploitation without consent",
                    "→ Surveillance technology for oppression",
                    "→ Social manipulation technologies",
                    "→ Authoritarian surveillance enablement",
                ],
            },
        },
    ]

    # Define conduct exclusions data
    conduct_exclusions = [
        {
            "type": "exclusion_category",
            "value": {
                "title": "Human Rights Violations",
                "items": [
                    "→ Labor rights violations",
                    "→ Child labor exploitation",
                    "→ Anti-union activities",
                    "→ Human trafficking involvement",
                    "→ Workplace safety negligence",
                    "→ Discrimination & harassment",
                ],
            },
        },
        {
            "type": "exclusion_category",
            "value": {
                "title": "Environmental Damage",
                "items": [
                    "→ Deforestation & habitat destruction",
                    "→ Climate change acceleration",
                    "→ Pollution & toxic waste",
                    "→ Environmental cover-ups",
                    "→ Ecosystem destruction",
                ],
            },
        },
        {
            "type": "exclusion_category",
            "value": {
                "title": "Corporate Misconduct",
                "items": [
                    "→ Corruption & bribery",
                    "→ Tax avoidance schemes",
                    "→ Consumer fraud",
                    "→ Regulatory capture attempts",
                    "→ Greenwashing & deception",
                ],
            },
        },
        {
            "type": "exclusion_category",
            "value": {
                "title": "Global Impact",
                "items": [
                    "→ Supply chain responsibility failures",
                    "→ International law violations",
                    "→ Community displacement",
                    "→ Indigenous rights violations",
                    "→ Developing nation exploitation",
                    "→ Predatory lending practices",
                ],
            },
        },
    ]

    # Update all ProcessPage instances
    for page in ProcessPage.objects.all():
        page.product_exclusions = product_exclusions
        page.conduct_exclusions = conduct_exclusions
        page.save()


def reverse_populate_process_page_fields(apps, schema_editor):
    ProcessPage = apps.get_model("public_site", "ProcessPage")

    for page in ProcessPage.objects.all():
        page.product_exclusions = []
        page.conduct_exclusions = []
        page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0007_add_process_page_fields"),
    ]

    operations = [
        migrations.RunPython(
            populate_process_page_fields, reverse_populate_process_page_fields
        ),
    ]
