# Generated by Django 5.1.5 on 2025-07-07 00:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0008_populate_process_page_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="hobbies",
            field=wagtail.fields.StreamField(
                [("hobby", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 10}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 500, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="experience_timeline",
            field=wagtail.fields.StreamField(
                [("timeline_item", 7)],
                blank=True,
                block_lookup={
                    3: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 500, "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("year", 3), ("company", 4), ("description", 5)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="featured_posts",
            field=wagtail.fields.StreamField(
                [("featured_post", 8)],
                blank=True,
                block_lookup={
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 2), ("url", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
