# Generated by Django 5.1.5 on 2025-07-07 00:06

from django.db import migrations


def populate_about_page_fields(apps, schema_editor):
    AboutPage = apps.get_model("public_site", "AboutPage")

    # Define timeline data
    timeline_data = [
        {
            "type": "timeline_item",
            "value": {
                "year": "2007-8",
                "company": "Oppenheimer & Co",
                "description": "",
            },
        },
        {
            "type": "timeline_item",
            "value": {"year": "2009", "company": "Family Office", "description": ""},
        },
        {
            "type": "timeline_item",
            "value": {"year": "2010-18", "company": "CFA Institute", "description": ""},
        },
        {
            "type": "timeline_item",
            "value": {
                "year": "2018-21",
                "company": "Independent Consultant",
                "description": "",
            },
        },
        {
            "type": "timeline_item",
            "value": {
                "year": "2021",
                "company": "Founded Ethical Capital",
                "description": "",
            },
        },
    ]

    # Define hobbies data
    hobbies_data = [
        {
            "type": "hobby",
            "value": {
                "icon": "⛷️",
                "title": "Skiing",
                "description": "Utah's many awesome resorts",
            },
        },
        {
            "type": "hobby",
            "value": {
                "icon": "🌻",
                "title": "Gardening",
                "description": "Replacing lawn with wildlife-friendly perennials",
            },
        },
    ]

    # Update all AboutPage instances
    for page in AboutPage.objects.all():
        page.experience_timeline = timeline_data
        page.hobbies = hobbies_data
        page.save()


def reverse_populate_about_page_fields(apps, schema_editor):
    AboutPage = apps.get_model("public_site", "AboutPage")

    for page in AboutPage.objects.all():
        page.experience_timeline = []
        page.hobbies = []
        page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0009_add_about_page_timeline_hobbies"),
    ]

    operations = [
        migrations.RunPython(
            populate_about_page_fields, reverse_populate_about_page_fields
        ),
    ]
