# Generated by Django 5.1.5 on 2025-07-07 00:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0010_populate_about_page_timeline_hobbies"),
    ]

    operations = [
        # What We Offer section
        migrations.AddField(
            model_name="advisorpage",
            name="offer_section_title",
            field=models.CharField(
                max_length=200,
                default="WHAT WE OFFER ADVISERS",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="offer_section_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We provide investment advisers with institutional-grade research capabilities and proven strategies to confidently serve clients who prioritize ethical investing, without compromising on performance or professionalism.</p>",
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="services_offered",
            field=wagtail.fields.StreamField(
                [("service", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 2)]],
                        {},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
        # Partnership Benefits section
        migrations.AddField(
            model_name="advisorpage",
            name="benefits_section_title",
            field=models.CharField(
                max_length=200,
                default="WHY ADVISERS CHOOSE US",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="benefits_section_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Leading investment advisers partner with us because we deliver the institutional-grade expertise and transparency their sophisticated clients demand.</p>",
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="partnership_benefits",
            field=wagtail.fields.StreamField(
                [("benefit", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 2)]],
                        {},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
        # Process Overview section
        migrations.AddField(
            model_name="advisorpage",
            name="process_section_title",
            field=models.CharField(
                max_length=200,
                default="OUR COLLABORATIVE APPROACH",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="process_steps",
            field=wagtail.fields.StreamField(
                [("process_step", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.IntegerBlock", (), {"min_value": 1}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("step_number", 1), ("title", 0), ("description", 4)]],
                        {},
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                },
            ),
        ),
        # Due Diligence Resources section
        migrations.AddField(
            model_name="advisorpage",
            name="ddq_section_title",
            field=models.CharField(
                max_length=200,
                default="DUE DILIGENCE RESOURCES",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="ddq_section_subtitle",
            field=models.CharField(
                max_length=200,
                default="Documentation for Investment Advisers",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="ddq_section_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Comprehensive documentation to support your due diligence process and adviser requirements.</p>",
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="resource_categories",
            field=wagtail.fields.StreamField(
                [("resource_category", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 10}),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 1), ("title", 0), ("description", 2), ("url", 2)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("resources", 6)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (3,), {}),
                },
            ),
        ),
        # CTA section
        migrations.AddField(
            model_name="advisorpage",
            name="cta_section_title",
            field=models.CharField(
                max_length=200,
                default="READY TO PARTNER?",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="cta_primary_text",
            field=models.CharField(
                max_length=100,
                default="SCHEDULE A CONSULTATION",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="cta_primary_url",
            field=models.URLField(
                blank=True,
                default="https://tidycal.com/ecic/adviser",
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="cta_secondary_text",
            field=models.CharField(
                max_length=100,
                default="SEND A MESSAGE",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="advisorpage",
            name="cta_secondary_url",
            field=models.CharField(
                max_length=200,
                default="/contact/",
                blank=True,
            ),
        ),
    ]