# Generated by Django 5.1.5 on 2025-07-04 07:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0011_fix_migration_state"),
        ("wagtailcore", "0095_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<p>Ethical Capital is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards.</p>",
                    ),
                ),
                (
                    "standards_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<h2>Conformance Status</h2>\n        <p>The Web Content Accessibility Guidelines (WCAG) defines requirements for designers and developers to improve accessibility for people with disabilities. It defines three levels of conformance: Level A, Level AA, and Level AAA. Ethical Capital is partially conformant with WCAG 2.1 level AA. Partially conformant means that some parts of the content do not fully conform to the accessibility standard.</p>",
                    ),
                ),
                (
                    "features_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<h2>Accessibility Features</h2>\n        <ul>\n            <li>Keyboard navigation support throughout the site</li>\n            <li>ARIA labels for screen reader compatibility</li>\n            <li>High contrast mode support</li>\n            <li>Resizable text without loss of functionality</li>\n            <li>Alternative text for all informative images</li>\n            <li>Consistent navigation structure</li>\n            <li>Clear focus indicators</li>\n        </ul>",
                    ),
                ),
                (
                    "feedback_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default='<h2>Feedback</h2>\n        <p>We welcome your feedback on the accessibility of Ethical Capital. Please let us know if you encounter accessibility barriers:</p>\n        <ul>\n            <li>Email: <a href="mailto:accessibility@ethicic.com">accessibility@ethicic.com</a></li>\n            <li>Contact form: <a href="/contact/">Contact us</a></li>\n        </ul>\n        <p>We try to respond to feedback within 2 business days.</p>',
                    ),
                ),
                (
                    "technical_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<h2>Technical Specifications</h2>\n        <p>Accessibility of Ethical Capital relies on the following technologies to work with the particular combination of web browser and any assistive technologies or plugins installed on your computer:</p>\n        <ul>\n            <li>HTML</li>\n            <li>CSS</li>\n            <li>JavaScript</li>\n            <li>ARIA</li>\n        </ul>",
                    ),
                ),
                (
                    "limitations_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<h2>Known Limitations</h2>\n        <p>Despite our best efforts to ensure accessibility of Ethical Capital, there may be some limitations. Below is a description of known limitations:</p>\n        <ul>\n            <li>Some older PDF documents may not be fully accessible. We are working to update these.</li>\n            <li>Some third-party content may not meet accessibility standards.</li>\n            <li>Some interactive charts may require additional assistance for screen reader users.</li>\n        </ul>",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accessibility Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsletterPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<p>Stay updated with the latest insights on ethical investing and portfolio management.</p>",
                    ),
                ),
                (
                    "benefits_title",
                    models.CharField(
                        blank=True, default="Why Subscribe?", max_length=200
                    ),
                ),
                (
                    "benefits_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<ul>\n            <li>Monthly market insights and ethical investing trends</li>\n            <li>Research updates and portfolio strategy discussions</li>\n            <li>Early access to new features and investment opportunities</li>\n            <li>Exclusive content not available on the website</li>\n        </ul>",
                    ),
                ),
                (
                    "privacy_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="<p>We respect your privacy. Your email will only be used for our newsletter and you can unsubscribe at any time.</p>",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
