# Generated by Django 5.1.5 on 2025-07-07 00:15

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0011_add_advisor_page_comprehensive_fields"),
    ]

    operations = [
        # What We Offer section
        migrations.AddField(
            model_name="institutionalpage",
            name="offer_section_title",
            field=models.CharField(
                max_length=200,
                default="WHAT WE OFFER INSTITUTIONS",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="offer_section_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We provide institutions with proven ethical investment strategies that can be implemented at scale using liquid securities. Our approach focuses on delivering strategies that meet fiduciary standards while achieving alignment with institutional values and stakeholder expectations.</p>",
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="services",
            field=wagtail.fields.StreamField(
                [("service", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 2)]],
                        {},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
        # Partnership Benefits section
        migrations.AddField(
            model_name="institutionalpage",
            name="benefits_section_title",
            field=models.CharField(
                max_length=200,
                default="WHY INSTITUTIONS CHOOSE US",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="benefits_section_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Leading institutions partner with us because we deliver proven strategies, transparent methodology, and direct access to decision-makers that institutional fiduciary standards demand.</p>",
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="benefits",
            field=wagtail.fields.StreamField(
                [("benefit", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 2)]],
                        {},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                },
            ),
        ),
        # Process Overview section
        migrations.AddField(
            model_name="institutionalpage",
            name="process_section_title",
            field=models.CharField(
                max_length=200,
                default="OUR INSTITUTIONAL APPROACH",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="process_steps",
            field=wagtail.fields.StreamField(
                [("process_step", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.IntegerBlock", (), {"min_value": 1}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("step_number", 1), ("title", 0), ("description", 4)]],
                        {},
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                },
            ),
        ),
        # Scale & Capabilities section
        migrations.AddField(
            model_name="institutionalpage",
            name="scale_section_title",
            field=models.CharField(
                max_length=200,
                default="INSTITUTIONAL SCALE & CAPABILITIES",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="scale_section_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our investment strategies and operational infrastructure are designed to support institutional-scale implementations with the rigor and transparency institutional oversight requires.</p>",
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="scale_metrics",
            field=wagtail.fields.StreamField(
                [("metric", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 0), ("label", 0), ("description", 4)]],
                        {},
                    ),
                },
            ),
        ),
        # Due Diligence Resources section
        migrations.AddField(
            model_name="institutionalpage",
            name="ddq_section_title",
            field=models.CharField(
                max_length=200,
                default="DUE DILIGENCE RESOURCES",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="ddq_section_subtitle",
            field=models.CharField(
                max_length=200,
                default="Documentation for Institutional Partners",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="ddq_section_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Comprehensive documentation to support your due diligence process and institutional requirements.</p>",
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="resource_categories",
            field=wagtail.fields.StreamField(
                [("resource_category", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 10}),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 1), ("title", 0), ("description", 2), ("url", 2)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (3,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("resources", 6)]],
                        {},
                    ),
                },
            ),
        ),
        # CTA section updates
        migrations.AddField(
            model_name="institutionalpage",
            name="cta_section_title",
            field=models.CharField(
                max_length=200,
                default="READY TO PARTNER?",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="cta_primary_text",
            field=models.CharField(
                max_length=100,
                default="SCHEDULE INSTITUTIONAL CONSULTATION",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="cta_primary_url",
            field=models.URLField(
                blank=True,
                default="https://tidycal.com/ecic/institutional",
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="cta_secondary_text",
            field=models.CharField(
                max_length=100,
                default="SEND A MESSAGE",
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="institutionalpage",
            name="cta_secondary_url",
            field=models.CharField(
                max_length=200,
                default="/contact/",
                blank=True,
            ),
        ),
    ]
