# Generated by Django 5.1.5 on 2025-07-07 00:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0013_populate_institutional_page_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="experience_timeline",
            field=wagtail.fields.StreamField(
                [("timeline_item", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Year or year range (e.g., 2007-8)",
                            "max_length": 20,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Company or organization name",
                            "max_length": 200,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional description",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("year", 0), ("company", 1), ("description", 2)]],
                        {},
                    ),
                },
                help_text="Experience timeline items",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_posts",
            field=wagtail.fields.StreamField(
                [("featured_post", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.TextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Link to the post", "max_length": 200},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("url", 2)]],
                        {},
                    ),
                },
                help_text="Featured writing posts",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="hobbies",
            field=wagtail.fields.StreamField(
                [("hobby", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Emoji icon for the hobby", "max_length": 10},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
                help_text="Personal hobbies and interests",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="partnership_benefits",
            field=wagtail.fields.StreamField(
                [("benefit", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                },
                help_text="Partnership benefits for advisers",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="process_steps",
            field=wagtail.fields.StreamField(
                [("process_step", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"min_value": 1}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("step_number", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
                help_text="Process steps for adviser collaboration",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="resource_categories",
            field=wagtail.fields.StreamField(
                [("resource_category", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Emoji icon", "max_length": 10},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 1), ("title", 0), ("description", 2), ("url", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("resources", 4)]],
                        {},
                    ),
                },
                help_text="Resource categories with links",
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_offered",
            field=wagtail.fields.StreamField(
                [("service", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                },
                help_text="Services offered to advisers",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="benefits",
            field=wagtail.fields.StreamField(
                [("benefit", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                },
                help_text="Partnership benefits for institutions",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="process_steps",
            field=wagtail.fields.StreamField(
                [("process_step", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"min_value": 1}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("step_number", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
                help_text="Process steps for institutional collaboration",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="resource_categories",
            field=wagtail.fields.StreamField(
                [("resource_category", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Emoji icon", "max_length": 10},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 1), ("title", 0), ("description", 2), ("url", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("resources", 4)]],
                        {},
                    ),
                },
                help_text="Resource categories with links",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_metrics",
            field=wagtail.fields.StreamField(
                [("metric", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    1: ("wagtail.blocks.TextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 0), ("label", 0), ("description", 1)]],
                        {},
                    ),
                },
                help_text="Scale and capability metrics",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="services",
            field=wagtail.fields.StreamField(
                [("service", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                },
                help_text="Services offered to institutions",
            ),
        ),
    ]
