# Generated by generate_remove_defaults_migration.py
from django.db import migrations
import django.db.models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0013_add_supportticket_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_image",
            field=django.db.models.URLField(
                max_length=200,
                blank=True,
                help_text="URL to headshot image",
                verbose_name="headshot image",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_alt_text",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Alt text for headshot image",
                verbose_name="headshot alt text",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Philosophy quote in the hero section",
                verbose_name="philosophy quote",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link",
            field=django.db.models.CharField(
                max_length=500,
                blank=True,
                help_text="Link for the philosophy quote attribution (can be relative or absolute URL)",
                verbose_name="philosophy quote link",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link_text",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Text for the philosophy quote link",
                verbose_name="philosophy quote link text",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="name",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Name and pronouns",
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Professional title",
                verbose_name="professional title",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="linkedin_url",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="linkedin url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="twitter_url",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="twitter url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="bluesky_url",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="bluesky url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="instagram_url",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="instagram url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="tiktok_url",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="tiktok url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_url",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="calendar url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="sec_info_url",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="sec info url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for professional background section",
                verbose_name="professional background title",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Professional background content",
                verbose_name="professional background content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for external roles section",
                verbose_name="external roles title",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="External roles and leadership content",
                verbose_name="external roles content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for speaking & writing section",
                verbose_name="speaking writing title",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Speaking & writing content",
                verbose_name="speaking writing content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_cta_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Call-to-action text for speaking section",
                verbose_name="speaking cta text",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_contact_note",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Contact note for speaking section",
                verbose_name="speaking contact note",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link",
            field=django.db.models.URLField(
                max_length=200,
                blank=True,
                help_text="Calendar booking link",
                verbose_name="calendar link",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link_text",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Text for calendar link",
                verbose_name="calendar link text",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link",
            field=django.db.models.EmailField(
                max_length=254,
                blank=True,
                help_text="Contact email address",
                verbose_name="email link",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link_text",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Text for email link",
                verbose_name="email link text",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for personal interests section",
                verbose_name="personal interests title",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Personal interests content",
                verbose_name="personal interests content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="current_role_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Current role description for What I Do Now panel",
                verbose_name="current role content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Philosophy description for What I Do Now panel",
                verbose_name="philosophy content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="client_focus_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Client focus description for What I Do Now panel",
                verbose_name="client focus content",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="featured post 1 title"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_description",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="featured post 1 description"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_url",
            field=django.db.models.CharField(
                max_length=500, blank=True, verbose_name="featured post 1 url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="featured post 2 title"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_description",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="featured post 2 description"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_url",
            field=django.db.models.CharField(
                max_length=500, blank=True, verbose_name="featured post 2 url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="featured post 3 title"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_description",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="featured post 3 description"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_url",
            field=django.db.models.CharField(
                max_length=500, blank=True, verbose_name="featured post 3 url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="featured post 4 title"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_description",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="featured post 4 description"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_url",
            field=django.db.models.CharField(
                max_length=500, blank=True, verbose_name="featured post 4 url"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_topics",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Topics covered in speaking engagements",
                verbose_name="speaking topics",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaker_bio_url",
            field=django.db.models.URLField(
                max_length=200,
                blank=True,
                help_text="URL to speaker bio PDF",
                verbose_name="speaker bio url",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="standards_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="standards text"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="features_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="features text"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="feedback_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="feedback text"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="technical_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="technical text"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="limitations_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="limitations text"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="hero title"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_subtitle",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="hero subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="hero description"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="services title"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="services content"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="benefits title"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="benefits content"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="technology title"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="technology content"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="cta title"
            ),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="cta description"
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="featured title"
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="featured description"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="author"
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Main headline",
                verbose_name="hero title",
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_subtitle",
            field=django.db.models.TextField(
                max_length=500,
                blank=True,
                help_text="Subtitle text below the main headline",
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="contact_email",
            field=django.db.models.EmailField(
                max_length=254,
                blank=True,
                help_text="Contact email for consultations",
                verbose_name="contact email",
            ),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="form_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="form description"
            ),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="thank_you_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="thank you title"
            ),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="thank_you_message",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="thank you message"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="email",
            field=django.db.models.EmailField(
                max_length=254, blank=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Main headline",
                verbose_name="hero title",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_subtitle",
            field=django.db.models.TextField(
                max_length=500,
                blank=True,
                help_text="Subtitle text below the main headline",
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_section_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for transparency section",
                verbose_name="transparency section title",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description of transparency approach",
                verbose_name="transparency description",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_benefits",
            field=django.db.models.TextField(
                blank=True,
                help_text="Benefits of transparency, one per line",
                verbose_name="transparency benefits",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="github_criteria_url",
            field=django.db.models.URLField(
                max_length=200,
                blank=True,
                help_text="URL to GitHub screening policy",
                verbose_name="github criteria url",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_section_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for exclusions section",
                verbose_name="exclusions section title",
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_note",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Note about exclusions",
                verbose_name="exclusions note",
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaentry",
            name="difficulty_level",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="difficulty level"
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_email",
            field=django.db.models.EmailField(
                max_length=254, blank=True, verbose_name="contact email"
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_phone",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="contact phone"
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_address",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="contact address"
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="meeting_link",
            field=django.db.models.URLField(
                max_length=200, blank=True, verbose_name="meeting link"
            ),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Main headline",
                verbose_name="hero title",
            ),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_subtitle",
            field=django.db.models.TextField(
                max_length=500,
                blank=True,
                help_text="Subtitle text below the main headline",
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_tagline",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="hero tagline"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=300,
                blank=True,
                help_text="Main homepage headline",
                verbose_name="hero title",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Hero description text",
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="excluded_percentage",
            field=django.db.models.CharField(
                max_length=10,
                blank=True,
                help_text="Percentage of S&P 500 excluded",
                verbose_name="excluded percentage",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="since_year",
            field=django.db.models.CharField(
                max_length=20,
                blank=True,
                help_text="Year established or founding info",
                verbose_name="since year",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="philosophy title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Investment philosophy description",
                verbose_name="philosophy content",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_highlight",
            field=django.db.models.CharField(
                max_length=300,
                blank=True,
                help_text="Key philosophy statement",
                verbose_name="philosophy highlight",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_section_header",
            field=django.db.models.CharField(
                max_length=100,
                blank=True,
                help_text="Section header for investment philosophy",
                verbose_name="philosophy section header",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_section_header",
            field=django.db.models.CharField(
                max_length=100,
                blank=True,
                help_text="Section header for principles",
                verbose_name="principles section header",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_section_header",
            field=django.db.models.CharField(
                max_length=100,
                blank=True,
                help_text="Section header for strategies",
                verbose_name="strategies section header",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_section_header",
            field=django.db.models.CharField(
                max_length=100,
                blank=True,
                help_text="Section header for process",
                verbose_name="process section header",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_section_header",
            field=django.db.models.CharField(
                max_length=100,
                blank=True,
                help_text="Section header for who we serve",
                verbose_name="serve section header",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_section_header",
            field=django.db.models.CharField(
                max_length=100,
                blank=True,
                help_text="Section header for call to action",
                verbose_name="cta section header",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_intro",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="principles intro"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="process principle 1 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="process principle 1 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="process principle 2 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="process principle 2 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="process principle 3 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="process principle 3 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="practice principle 1 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="practice principle 1 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="practice principle 2 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="practice principle 2 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="practice principle 3 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="practice principle 3 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_intro",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="strategies intro"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="process title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="process step 1 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="process step 1 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="process step 2 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="process step 2 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="process step 3 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="process step 3 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="process step 4 title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="process step 4 content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="serve individual title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="serve individual content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="serve advisor title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="serve advisor content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_title",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="serve institution title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_content",
            field=django.db.models.TextField(
                blank=True, verbose_name="serve institution content"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="cta title"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="cta description"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="minimum_investment_text",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="minimum investment text"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="client_availability_text",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="client availability text"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="disclaimer_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Legal disclaimer and footnotes",
                verbose_name="disclaimer text",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="hero title"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_subtitle",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="hero subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="hero description"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="solutions title"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="solutions content"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="capabilities_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="capabilities title"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="scale title"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="scale content"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="cta title"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="cta description"
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Introduction text that appears at the top of the media page",
                verbose_name="intro text",
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="press_kit_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for the press kit section",
                verbose_name="press kit title",
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="benefits_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="benefits title"
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="benefits_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="benefits text"
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="privacy_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="privacy text"),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="form_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="form description"
            ),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="thank you title"
            ),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_message",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="thank you message"
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Main headline",
                verbose_name="hero title",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_subtitle",
            field=django.db.models.TextField(
                max_length=500,
                blank=True,
                help_text="Subtitle text below the main headline",
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Hero section description",
                verbose_name="hero description",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="updated_at",
            field=django.db.models.CharField(
                max_length=50,
                blank=True,
                help_text="Month and year when this document was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="executive_summary",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Executive summary of ESG approach",
                verbose_name="executive summary",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="screening_policy_url",
            field=django.db.models.URLField(
                max_length=200,
                blank=True,
                help_text="URL to open-source screening policy",
                verbose_name="screening policy url",
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="form_adv_url",
            field=django.db.models.URLField(
                max_length=200,
                blank=True,
                help_text="URL to Form ADV disclosure",
                verbose_name="form adv url",
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="enterprise_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="enterprise title"
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="contact_cta",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="contact cta"),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="process_overview",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="process overview"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="step1 title"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="step1 content"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="step2 title"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="step2 content"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="step3 title"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="step3 content"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="step4 title"
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="step4 content"
            ),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="featured title"
            ),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="featured description"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Main headline",
                verbose_name="hero title",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_subtitle",
            field=django.db.models.TextField(
                max_length=500,
                blank=True,
                help_text="Subtitle text below the main headline",
                verbose_name="hero subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Hero section description",
                verbose_name="hero description",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="strategies_section_title",
            field=django.db.models.CharField(
                max_length=200,
                blank=True,
                help_text="Title for strategies section",
                verbose_name="strategies section title",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="strategies_intro",
            field=django.db.models.TextField(
                blank=True,
                help_text="Introduction text for strategies section",
                verbose_name="strategies intro",
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="individuals_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="individuals title"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="individuals_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="individuals content"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="institutions_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="institutions title"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="institutions_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="institutions content"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="advisors_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="advisors title"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="advisors_content",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="advisors content"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="cta_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="cta title"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="cta description"
            ),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="intro text"),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="comparison title"
            ),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_description",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="comparison description"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="risk_level",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="risk level"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ethical_implementation",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="ethical implementation"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="holdings_count",
            field=django.db.models.CharField(
                max_length=50, blank=True, verbose_name="holdings count"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="best_for",
            field=django.db.models.CharField(
                max_length=100, blank=True, verbose_name="best for"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="cash_allocation",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="cash allocation"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="benchmark_name",
            field=django.db.models.CharField(
                max_length=50,
                blank=True,
                help_text="e.g., ACWI, AGG/PFF, S&P 500",
                verbose_name="benchmark name",
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_return",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="ytd return"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_benchmark",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="ytd benchmark"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_difference",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="ytd difference"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_return",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="one year return"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_benchmark",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="one year benchmark"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_difference",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="one year difference"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_return",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="three year return"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_benchmark",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="three year benchmark"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_difference",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="three year difference"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_return",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="since inception return"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_benchmark",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="since inception benchmark"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_difference",
            field=django.db.models.CharField(
                max_length=20, blank=True, verbose_name="since inception difference"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="overweights_note",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="overweights note"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="exclusions_note",
            field=django.db.models.CharField(
                max_length=300, blank=True, verbose_name="exclusions note"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="healthcare_exclusion_note",
            field=django.db.models.TextField(
                blank=True, verbose_name="healthcare exclusion note"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="commentary_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="commentary title"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="process_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="process title"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="documents_title",
            field=django.db.models.CharField(
                max_length=200, blank=True, verbose_name="documents title"
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="performance_disclaimer",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="performance disclaimer"
            ),
        ),
    ]
