# Generated by Django 5.1.5 on 2025-07-07 00:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0014_add_contact_page_comprehensive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformpage",
            name="business_hours",
            field=models.CharField(
                blank=True,
                default="Monday - Friday, 9:00 AM - 5:00 PM MT",
                help_text="Business hours",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="consultation_sidebar_button_text",
            field=models.CharField(blank=True, default="SCHEDULE NOW", max_length=100),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="consultation_sidebar_button_url",
            field=models.CharField(
                blank=True, default="/consultation/", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="consultation_sidebar_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Get personalized guidance on ethical investing. Schedule a free consultation to discuss your investment goals and values.</p>",
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="consultation_sidebar_title",
            field=models.CharField(
                blank=True, default="SCHEDULE A CONSULTATION", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="contact_address",
            field=models.CharField(
                blank=True,
                default="90 N 400 E, Provo, UT 84606",
                help_text="Business address",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                default="hello@ethicic.com",
                help_text="Primary contact email address",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="+1 347 625 9000",
                help_text="Primary contact phone number",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="contact_section_title",
            field=models.CharField(
                blank=True, default="CONTACT INFORMATION", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="show_consultation_sidebar",
            field=models.BooleanField(
                default=True, help_text="Show consultation scheduling sidebar"
            ),
        ),
    ]
