# Generated by Django 5.1.5 on 2025-07-04 11:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0014_remove_hardcoded_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="bluesky_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link",
            field=models.URLField(blank=True, help_text="Calendar booking link"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link_text",
            field=models.CharField(
                blank=True, help_text="Text for calendar link", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="client_focus_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Client focus description for What I Do Now panel"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="current_role_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Current role description for What I Do Now panel"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link",
            field=models.EmailField(
                blank=True, help_text="Contact email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link_text",
            field=models.CharField(
                blank=True, help_text="Text for email link", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="External roles and leadership content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_title",
            field=models.CharField(
                blank=True, help_text="Title for external roles section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_alt_text",
            field=models.CharField(
                blank=True, help_text="Alt text for headshot image", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_image",
            field=models.URLField(blank=True, help_text="URL to headshot image"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name and pronouns", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Personal interests content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_title",
            field=models.CharField(
                blank=True,
                help_text="Title for personal interests section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Philosophy description for What I Do Now panel"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Philosophy quote in the hero section"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link",
            field=models.CharField(
                blank=True,
                help_text="Link for the philosophy quote attribution (can be relative or absolute URL)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link_text",
            field=models.CharField(
                blank=True,
                help_text="Text for the philosophy quote link",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Professional background content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_title",
            field=models.CharField(
                blank=True,
                help_text="Title for professional background section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_title",
            field=models.CharField(
                blank=True, help_text="Professional title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="sec_info_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaker_bio_url",
            field=models.URLField(blank=True, help_text="URL to speaker bio PDF"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_contact_note",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Contact note for speaking section"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_cta_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Call-to-action text for speaking section"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_topics",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Topics covered in speaking engagements"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Speaking & writing content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_title",
            field=models.CharField(
                blank=True,
                help_text="Title for speaking & writing section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="features_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="feedback_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="limitations_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="standards_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="accessibilitypage",
            name="technical_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="contact_email",
            field=models.EmailField(
                blank=True, help_text="Contact email for consultations", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_subtitle",
            field=models.TextField(
                help_text="Subtitle text below the main headline", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_title",
            field=models.CharField(help_text="Main headline", max_length=200),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="form_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="thank_you_message",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactformpage",
            name="thank_you_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_note",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Note about exclusions"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_section_title",
            field=models.CharField(
                blank=True, help_text="Title for exclusions section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="github_criteria_url",
            field=models.URLField(help_text="URL to GitHub screening policy"),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_subtitle",
            field=models.TextField(
                help_text="Subtitle text below the main headline", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_title",
            field=models.CharField(help_text="Main headline", max_length=200),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_benefits",
            field=models.TextField(
                blank=True, help_text="Benefits of transparency, one per line"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Description of transparency approach"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_section_title",
            field=models.CharField(
                blank=True, help_text="Title for transparency section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaentry",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="exclusioncategory",
            name="icon",
            field=models.CharField(help_text="Emoji icon for category", max_length=10),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_subtitle",
            field=models.TextField(
                help_text="Subtitle text below the main headline", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_title",
            field=models.CharField(help_text="Main headline", max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="client_availability_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_section_header",
            field=models.CharField(
                blank=True,
                help_text="Section header for call to action",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="disclaimer_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Legal disclaimer and footnotes"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="excluded_percentage",
            field=models.CharField(
                blank=True, help_text="Percentage of S&P 500 excluded", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Hero description text"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_tagline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(help_text="Main homepage headline", max_length=300),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="minimum_investment_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Investment philosophy description"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_highlight",
            field=models.CharField(
                blank=True, help_text="Key philosophy statement", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_section_header",
            field=models.CharField(
                blank=True,
                help_text="Section header for investment philosophy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for principles", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for process", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for who we serve", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="since_year",
            field=models.CharField(
                blank=True, help_text="Year established or founding info", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for strategies", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="capabilities_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Introduction text that appears at the top of the media page",
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="press_kit_title",
            field=models.CharField(
                blank=True, help_text="Title for the press kit section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="benefits_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="benefits_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="newsletterpage",
            name="privacy_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="form_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_message",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="contact_cta",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="enterprise_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="executive_summary",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Executive summary of ESG approach"
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="form_adv_url",
            field=models.URLField(blank=True, help_text="URL to Form ADV disclosure"),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Hero section description"
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_subtitle",
            field=models.TextField(
                help_text="Subtitle text below the main headline", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_title",
            field=models.CharField(help_text="Main headline", max_length=200),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="screening_policy_url",
            field=models.URLField(help_text="URL to open-source screening policy"),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="updated_at",
            field=models.CharField(
                help_text="Month and year when this document was last updated",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="process_overview",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="accessibility_phone",
            field=models.CharField(
                help_text="Accessibility support phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="business_hours",
            field=models.CharField(
                help_text="Business hours display text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="cio_email",
            field=models.EmailField(
                help_text="Chief Investment Officer email", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="city",
            field=models.CharField(help_text="City", max_length=100),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company_description",
            field=models.TextField(
                help_text="Company description for meta tags and schema markup"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company_name",
            field=models.CharField(
                help_text="Company brand name displayed in navigation and footer",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company_tagline",
            field=models.CharField(
                help_text="Main tagline for SEO and social media", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_error_message",
            field=models.TextField(
                help_text="Error message for contact form submissions"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_success_message",
            field=models.TextField(
                help_text="Success message for contact form submissions"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="copyright_text",
            field=models.CharField(help_text="Footer copyright text", max_length=200),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="country",
            field=models.CharField(help_text="Country", max_length=100),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="default_meta_description",
            field=models.TextField(
                help_text="Default meta description for pages without custom descriptions"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="founding_year",
            field=models.CharField(help_text="Company founding year", max_length=4),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_balanced_desc",
            field=models.TextField(help_text="Balanced investment goal description"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_balanced_title",
            field=models.CharField(
                help_text="Balanced investment goal title", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_growth_desc",
            field=models.TextField(help_text="Growth investment goal description"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_growth_title",
            field=models.CharField(
                help_text="Growth investment goal title", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_income_desc",
            field=models.TextField(help_text="Income investment goal description"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_income_title",
            field=models.CharField(
                help_text="Income investment goal title", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_preservation_desc",
            field=models.TextField(
                help_text="Preservation investment goal description"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="investment_goal_preservation_title",
            field=models.CharField(
                help_text="Preservation investment goal title", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="meta_keywords",
            field=models.CharField(help_text="Default meta keywords", max_length=300),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="minimum_investment",
            field=models.CharField(
                help_text="Minimum investment amount", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_description",
            field=models.TextField(help_text="Newsletter signup description"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_privacy_text",
            field=models.CharField(
                help_text="Newsletter privacy notice", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_success_message",
            field=models.TextField(
                help_text="Success message for newsletter subscriptions"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="newsletter_title",
            field=models.CharField(
                help_text="Newsletter signup widget title", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="postal_code",
            field=models.CharField(help_text="Postal/ZIP code", max_length=20),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_email",
            field=models.EmailField(
                help_text="Primary contact email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_phone",
            field=models.CharField(help_text="Primary phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="state",
            field=models.CharField(help_text="State or region", max_length=50),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="street_address",
            field=models.CharField(help_text="Street address", max_length=200),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="support_email",
            field=models.EmailField(
                help_text="Support and accessibility contact email", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="twitter_handle",
            field=models.CharField(
                help_text="Twitter handle (include @)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="advisors_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="advisors_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Hero section description"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_subtitle",
            field=models.TextField(
                help_text="Subtitle text below the main headline", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="hero_title",
            field=models.CharField(help_text="Main headline", max_length=200),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="individuals_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="individuals_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="institutions_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="institutions_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="strategies_intro",
            field=models.TextField(
                blank=True, help_text="Introduction text for strategies section"
            ),
        ),
        migrations.AlterField(
            model_name="solutionspage",
            name="strategies_section_title",
            field=models.CharField(
                blank=True, help_text="Title for strategies section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="strategycard",
            name="icon",
            field=models.CharField(help_text="Emoji icon for strategy", max_length=10),
        ),
        migrations.AlterField(
            model_name="strategydocument",
            name="icon",
            field=models.CharField(help_text="Emoji icon for document", max_length=10),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="benchmark_name",
            field=models.CharField(
                blank=True, help_text="e.g., ACWI, AGG/PFF, S&P 500", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="best_for",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="cash_allocation",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="commentary_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="documents_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ethical_implementation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="exclusions_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="healthcare_exclusion_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="holdings_count",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_benchmark",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_difference",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="one_year_return",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="overweights_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="performance_disclaimer",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="process_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="risk_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_benchmark",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_difference",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="since_inception_return",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_benchmark",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_difference",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="three_year_return",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_benchmark",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_difference",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="ytd_return",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("contact", "Contact Form"),
                    ("newsletter", "Newsletter Signup"),
                    ("onboarding", "Onboarding Request"),
                    ("garden_interest", "Garden Platform Interest"),
                ],
                max_length=20,
            ),
        ),
    ]
