# Generated by Django 5.1.5 on 2025-07-07 00:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0015_add_contact_form_info_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationpage",
            name="alternative_contact_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default='<p>Prefer to start with an email? <a href="/contact/" class="garden-link">Use our contact form</a> and we\'ll get back to you when we can.</p>',
            ),
        ),
        migrations.AddField(
            model_name="consultationpage",
            name="consultation_types",
            field=wagtail.fields.StreamField(
                [("consultation_type", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Emoji icon", "max_length": 10},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Schedule Call", "max_length": 50},
                    ),
                    4: ("wagtail.blocks.URLBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 0),
                                ("title", 1),
                                ("description", 2),
                                ("button_text", 3),
                                ("button_url", 4),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Different consultation types available",
            ),
        ),
        migrations.AddField(
            model_name="consultationpage",
            name="disclaimer_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We believe in finding the right fit for both parties. There's no pressure to move forward, and we're happy to answer questions even if we're not the right match.</p>",
            ),
        ),
        migrations.AddField(
            model_name="consultationpage",
            name="disclaimer_title",
            field=models.CharField(
                blank=True, default="No obligation consultation.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="consultationpage",
            name="expectations",
            field=wagtail.fields.StreamField(
                [("expectation", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.TextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1)]],
                        {},
                    ),
                },
                help_text="What to expect during consultation",
            ),
        ),
        migrations.AddField(
            model_name="consultationpage",
            name="expectations_section_title",
            field=models.CharField(
                blank=True, default="What to Expect", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="consultationpage",
            name="schedule_intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Choose the conversation type that best fits your situation. All consultations are complimentary and without obligation. Note: We can't promise prompt email responses, but we're great at keeping scheduled appointments!</p>",
            ),
        ),
        migrations.AddField(
            model_name="consultationpage",
            name="schedule_section_title",
            field=models.CharField(
                blank=True, default="Schedule Your Consultation", max_length=200
            ),
        ),
    ]
