# Generated by Django 5.1.5 on 2025-07-07 00:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0017_populate_consultation_page_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapage",
            name="empty_state_message",
            field=wagtail.fields.RichTextField(
                blank=True,
                default='<p>For press inquiries, please <a href="/contact-form/">contact us directly</a>.</p>',
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="empty_state_title",
            field=models.CharField(
                blank=True, default="NO MEDIA COVERAGE YET", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_contact_button_text",
            field=models.CharField(blank=True, default="CONTACT US", max_length=100),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_contact_button_url",
            field=models.CharField(blank=True, default="/contact/", max_length=200),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_contact_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>For press inquiries and additional information.</p>",
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_contact_show",
            field=models.BooleanField(
                default=True, help_text="Show media contact sidebar section"
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_contact_title",
            field=models.CharField(blank=True, default="MEDIA CONTACT", max_length=200),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_interview_button_text",
            field=models.CharField(
                blank=True, default="BOOK INTERVIEW", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_interview_button_url",
            field=models.URLField(
                blank=True, default="https://tidycal.com/ecic/interview"
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_interview_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Book a time to speak with our Chief Investment Officer about sustainable investing and our mission.</p>",
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_interview_show",
            field=models.BooleanField(
                default=True, help_text="Show schedule interview sidebar section"
            ),
        ),
        migrations.AddField(
            model_name="mediapage",
            name="sidebar_interview_title",
            field=models.CharField(
                blank=True, default="SCHEDULE INTERVIEW", max_length=200
            ),
        ),
    ]
