# Generated by Django 5.1.5 on 2025-07-07 00:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0018_add_media_page_sidebar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategylistpage",
            name="cta_buttons",
            field=wagtail.fields.StreamField(
                [("cta_button", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 1), ("style", 2)]],
                        {},
                    ),
                },
                help_text="Call to action buttons",
            ),
        ),
        migrations.AddField(
            model_name="strategylistpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Our team is here to help you choose the strategy that best fits your financial goals and ethical principles.</p>",
            ),
        ),
        migrations.AddField(
            model_name="strategylistpage",
            name="cta_section_title",
            field=models.CharField(blank=True, default="GET STARTED", max_length=200),
        ),
        migrations.AddField(
            model_name="strategylistpage",
            name="cta_title",
            field=models.CharField(
                blank=True,
                default="Ready to Align Your Investments with Your Values?",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="strategylistpage",
            name="resources",
            field=wagtail.fields.StreamField(
                [("resource_category", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.TextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    3: ("wagtail.blocks.StructBlock", [[("text", 0), ("url", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("links", 4)]],
                        {},
                    ),
                },
                help_text="Resource categories with links",
            ),
        ),
        migrations.AddField(
            model_name="strategylistpage",
            name="resources_section_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Learn more about our investment approach, methodology, and compliance practices.</p>",
            ),
        ),
        migrations.AddField(
            model_name="strategylistpage",
            name="resources_section_subtitle",
            field=models.CharField(
                blank=True, default="Documentation & Research", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="strategylistpage",
            name="resources_section_title",
            field=models.CharField(
                blank=True, default="STRATEGY RESOURCES", max_length=200
            ),
        ),
    ]
