# Generated by Django 5.1.5 on 2025-07-07 00:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0020_populate_strategy_list_resources_cta"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqpage",
            name="empty_state_button_text",
            field=models.CharField(blank=True, default="Contact Us", max_length=100),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="empty_state_button_url",
            field=models.CharField(blank=True, default="/contact/", max_length=200),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="empty_state_message",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>We're building our FAQ section. In the meantime, please don't hesitate to contact us directly with any questions.</p>",
            ),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="empty_state_title",
            field=models.CharField(
                blank=True, default="No FAQs Available", max_length=200
            ),
        ),
    ]
