# Generated by Django 5.1.5 on 2025-07-07 00:36

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0021_add_faq_page_empty_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidepage",
            name="description_section_header",
            field=models.CharField(
                blank=True, default="What's Included", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="download_section_header",
            field=models.CharField(
                blank=True, default="Download Guide", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="newsletter_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Get updates on new resources, market insights, and ethical investing research.</p>",
            ),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="newsletter_section_header",
            field=models.CharField(blank=True, default="Stay Updated", max_length=200),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="resources",
            field=wagtail.fields.StreamField(
                [("resource", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    1: ("wagtail.blocks.TextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Learn More", "max_length": 50},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("button_text", 2),
                                ("button_url", 3),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Additional resource links",
            ),
        ),
        migrations.AddField(
            model_name="guidepage",
            name="resources_section_header",
            field=models.CharField(
                blank=True, default="Additional Resources", max_length=200
            ),
        ),
    ]
