# Generated by Django 5.1.5 on 2025-07-07 00:37

from django.db import migrations
import json


def populate_guide_page_fields(apps, schema_editor):
    """Populate GuidePage with hardcoded content from template."""
    GuidePage = apps.get_model("public_site", "GuidePage")

    # Get all GuidePage instances
    for page in GuidePage.objects.all():
        # Resources
        if not page.resources:
            page.resources = json.dumps(
                [
                    {
                        "type": "resource",
                        "value": {
                            "title": "Our Process",
                            "description": "Learn about our three-step ethical investment approach.",
                            "button_text": "View Process",
                            "button_url": "/process/",
                        },
                    },
                    {
                        "type": "resource",
                        "value": {
                            "title": "Investment Strategies",
                            "description": "Explore our three core strategies and how they can be combined.",
                            "button_text": "View Strategies",
                            "button_url": "/strategies/",
                        },
                    },
                    {
                        "type": "resource",
                        "value": {
                            "title": "Screening Criteria",
                            "description": "Review our transparent, open-source ethical screening criteria.",
                            "button_text": "View Criteria",
                            "button_url": "/criteria/",
                        },
                    },
                    {
                        "type": "resource",
                        "value": {
                            "title": "Schedule Consultation",
                            "description": "Discuss how our approach might fit your investment goals.",
                            "button_text": "Schedule Call",
                            "button_url": "/consultation/",
                        },
                    },
                ]
            )

        page.save()


def reverse_population(apps, schema_editor):
    """Reverse migration - no need to clear fields."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0022_add_guide_page_resources_headers"),
    ]

    operations = [
        migrations.RunPython(populate_guide_page_fields, reverse_population),
    ]
