# Generated by Django 5.1.5 on 2025-07-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0023_populate_guide_page_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_additional",
            field=models.CharField(
                blank=True,
                default="Additional Information",
                help_text="Section subtitle for additional information",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_climate",
            field=models.CharField(
                blank=True,
                default="Climate & Environmental Considerations",
                help_text="Section subtitle for climate",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_esg",
            field=models.CharField(
                blank=True,
                default="ESG Integration Methodology",
                help_text="Section subtitle for ESG integration",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_executive",
            field=models.CharField(
                blank=True,
                default="Responsible Investment Overview",
                help_text="Section subtitle for executive summary",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_reporting",
            field=models.CharField(
                blank=True,
                default="Reporting and Verification",
                help_text="Section subtitle for reporting",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_stewardship",
            field=models.CharField(
                blank=True,
                default="Active Stewardship Practices",
                help_text="Section subtitle for stewardship",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_strategy",
            field=models.CharField(
                blank=True,
                default="Responsible Investment Strategy & Governance",
                help_text="Section subtitle for strategy section",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_subtitle_transparency",
            field=models.CharField(
                blank=True,
                default="Transparency & Disclosure",
                help_text="Section subtitle for transparency",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_additional",
            field=models.CharField(
                blank=True,
                default="ADDITIONAL INFORMATION",
                help_text="Panel title for additional information section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_climate",
            field=models.CharField(
                blank=True,
                default="CLIMATE & ENVIRONMENT",
                help_text="Panel title for climate section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_esg",
            field=models.CharField(
                blank=True,
                default="ESG INTEGRATION",
                help_text="Panel title for ESG integration section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_executive",
            field=models.CharField(
                blank=True,
                default="EXECUTIVE SUMMARY",
                help_text="Panel title for executive summary section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_overview",
            field=models.CharField(
                blank=True,
                default="PRI DUE DILIGENCE",
                help_text="Panel title for overview section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_reporting",
            field=models.CharField(
                blank=True,
                default="REPORTING AND VERIFICATION",
                help_text="Panel title for reporting section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_stewardship",
            field=models.CharField(
                blank=True,
                default="STEWARDSHIP & ENGAGEMENT",
                help_text="Panel title for stewardship section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_strategy",
            field=models.CharField(
                blank=True,
                default="STRATEGY & GOVERNANCE",
                help_text="Panel title for strategy section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="priddqpage",
            name="section_title_transparency",
            field=models.CharField(
                blank=True,
                default="TRANSPARENCY",
                help_text="Panel title for transparency section",
                max_length=100,
            ),
        ),
    ]
