# Generated by Django 5.1.5 on 2025-07-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0024_add_pri_ddq_section_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="accepting_clients_icon",
            field=models.CharField(
                blank=True,
                default="🟢",
                help_text="Icon for accepting clients indicator",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_button_1_link",
            field=models.CharField(
                blank=True,
                default="/consultation/",
                help_text="Bottom CTA first button link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_button_1_text",
            field=models.CharField(
                blank=True,
                default="SCHEDULE CONSULTATION",
                help_text="Bottom CTA first button text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_button_2_link",
            field=models.CharField(
                blank=True,
                default="/process/",
                help_text="Bottom CTA second button link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_button_2_text",
            field=models.CharField(
                blank=True,
                default="VIEW OUR PROCESS",
                help_text="Bottom CTA second button text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_1_link",
            field=models.CharField(
                blank=True,
                default="/consultation/",
                help_text="First hero CTA link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_1_text",
            field=models.CharField(
                blank=True,
                default="Schedule Consultation",
                help_text="First hero CTA link text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_2_link",
            field=models.CharField(
                blank=True,
                default="/process/",
                help_text="Second hero CTA link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_2_text",
            field=models.CharField(
                blank=True,
                default="View Our Process",
                help_text="Second hero CTA link text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_stats_date",
            field=models.CharField(
                blank=True,
                default="as of July 1, 2025",
                help_text="Date text for hero statistics",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="practice_subsection_header",
            field=models.CharField(
                blank=True,
                default="PRACTICE",
                help_text="Practice subsection header in principles",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="process_section_link",
            field=models.CharField(
                blank=True,
                default="/process/",
                help_text="Process section link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="process_section_link_text",
            field=models.CharField(
                blank=True,
                default="View Complete Methodology →",
                help_text="Process section link text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="process_subsection_header",
            field=models.CharField(
                blank=True,
                default="PROCESS",
                help_text="Process subsection header in principles",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="serve_advisor_link",
            field=models.CharField(
                blank=True,
                default="/advisers/",
                help_text="Financial advisors link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="serve_advisor_link_text",
            field=models.CharField(
                blank=True,
                default="Partner With Us →",
                help_text="Financial advisors link text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="serve_individual_link",
            field=models.CharField(
                blank=True,
                default="/onboarding/",
                help_text="Individual investors link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="serve_individual_link_text",
            field=models.CharField(
                blank=True,
                default="Start Your Journey →",
                help_text="Individual investors link text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="serve_institution_link",
            field=models.CharField(
                blank=True,
                default="/institutions/",
                help_text="Institutions link URL",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="serve_institution_link_text",
            field=models.CharField(
                blank=True,
                default="Institutional Solutions →",
                help_text="Institutions link text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_description",
            field=models.TextField(
                blank=True,
                default="Concentrated ethical portfolios built from individual securities. Our most comprehensive approach with full transparency and direct ownership.",
                help_text="Description for growth strategy",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_focus",
            field=models.CharField(
                blank=True,
                default="15-25 Companies",
                help_text="Focus value for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_link",
            field=models.CharField(
                blank=True,
                default="/strategies/growth/",
                help_text="Link URL for growth strategy",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_link_text",
            field=models.CharField(
                blank=True,
                default="Explore Growth Strategy →",
                help_text="Link text for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_management",
            field=models.CharField(
                blank=True,
                default="Active & Continuous",
                help_text="Management value for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_name",
            field=models.CharField(
                blank=True,
                default="Growth Strategy",
                help_text="Name of the first strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_ownership",
            field=models.CharField(
                blank=True,
                default="Direct Securities",
                help_text="Ownership value for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_screening",
            field=models.CharField(
                blank=True,
                default="Full Implementation",
                help_text="Screening value for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_1_subtitle",
            field=models.CharField(
                blank=True,
                default="Our Flagship Approach",
                help_text="Subtitle for first strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_description",
            field=models.TextField(
                blank=True,
                default="Fixed income portfolios screened for ethics and optimized for yield. Bonds, preferreds, and other income securities meeting our standards.",
                help_text="Description for income strategy",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_focus",
            field=models.CharField(
                blank=True,
                default="Income Generation",
                help_text="Focus value for income strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_link",
            field=models.CharField(
                blank=True,
                default="/strategies/income/",
                help_text="Link URL for income strategy",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_link_text",
            field=models.CharField(
                blank=True,
                default="Explore Income Strategy →",
                help_text="Link text for income strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_management",
            field=models.CharField(
                blank=True,
                default="Active & Continuous",
                help_text="Management value for income strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_name",
            field=models.CharField(
                blank=True,
                default="Income Strategy",
                help_text="Name of the second strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_ownership",
            field=models.CharField(
                blank=True,
                default="Direct Securities",
                help_text="Ownership value for income strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_screening",
            field=models.CharField(
                blank=True,
                default="Full Implementation",
                help_text="Screening value for income strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_2_subtitle",
            field=models.CharField(
                blank=True,
                default="Ethics Meets Yield",
                help_text="Subtitle for second strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_description",
            field=models.TextField(
                blank=True,
                default="Access broader market exposure through carefully selected ethical funds. For clients needing wider diversification while maintaining values alignment.",
                help_text="Description for diversification strategy",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_focus",
            field=models.CharField(
                blank=True,
                default="Broader Markets",
                help_text="Focus value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_link",
            field=models.CharField(
                blank=True,
                default="/strategies/diversification/",
                help_text="Link URL for diversification strategy",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_link_text",
            field=models.CharField(
                blank=True,
                default="Explore Diversification Strategy →",
                help_text="Link text for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_management",
            field=models.CharField(
                blank=True,
                default="Active & Continuous",
                help_text="Management value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_name",
            field=models.CharField(
                blank=True,
                default="Diversification Strategy",
                help_text="Name of the third strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_ownership",
            field=models.CharField(
                blank=True,
                default="External Funds",
                help_text="Ownership value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_screening",
            field=models.CharField(
                blank=True,
                default="Ethical Alignment",
                help_text="Screening value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_3_subtitle",
            field=models.CharField(
                blank=True,
                default="Discretionary Management",
                help_text="Subtitle for third strategy",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_label_focus",
            field=models.CharField(
                blank=True,
                default="Focus:",
                help_text="Label for strategy focus row",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_label_management",
            field=models.CharField(
                blank=True,
                default="Management:",
                help_text="Label for strategy management row",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_label_ownership",
            field=models.CharField(
                blank=True,
                default="What you own:",
                help_text="Label for strategy ownership row",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="strategy_label_screening",
            field=models.CharField(
                blank=True,
                default="Screening:",
                help_text="Label for strategy screening row",
                max_length=50,
            ),
        ),
    ]
