# Generated by Django 5.1.5 on 2025-07-11 21:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0025_homepage_accepting_clients_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="accepting_clients_icon",
            field=models.CharField(
                blank=True,
                help_text="Icon for accepting clients indicator",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="client_availability_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_button_1_link",
            field=models.CharField(
                blank=True, help_text="Bottom CTA first button link URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_button_1_text",
            field=models.CharField(
                blank=True, help_text="Bottom CTA first button text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_button_2_link",
            field=models.CharField(
                blank=True,
                help_text="Bottom CTA second button link URL",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_button_2_text",
            field=models.CharField(
                blank=True, help_text="Bottom CTA second button text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_section_header",
            field=models.CharField(
                blank=True,
                help_text="Section header for call to action",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="disclaimer_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Legal disclaimer and footnotes"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="excluded_percentage",
            field=models.CharField(
                blank=True, help_text="Percentage of S&P 500 excluded", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_cta_1_link",
            field=models.CharField(
                blank=True, help_text="First hero CTA link URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_cta_1_text",
            field=models.CharField(
                blank=True, help_text="First hero CTA link text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_cta_2_link",
            field=models.CharField(
                blank=True, help_text="Second hero CTA link URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_cta_2_text",
            field=models.CharField(
                blank=True, help_text="Second hero CTA link text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_stats_date",
            field=models.CharField(
                blank=True, help_text="Date text for hero statistics", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_subtitle",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Hero description text"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_tagline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                blank=True, help_text="Main homepage headline", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="minimum_investment_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Investment philosophy description"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_highlight",
            field=models.CharField(
                blank=True, help_text="Key philosophy statement", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_section_header",
            field=models.CharField(
                blank=True,
                help_text="Section header for investment philosophy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="philosophy_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_1_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_2_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_principle_3_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="practice_subsection_header",
            field=models.CharField(
                blank=True,
                help_text="Practice subsection header in principles",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="principles_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for principles", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_1_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_2_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_principle_3_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for process", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_section_link",
            field=models.CharField(
                blank=True, help_text="Process section link URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_section_link_text",
            field=models.CharField(
                blank=True, help_text="Process section link text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_1_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_2_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_3_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_step_4_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_subsection_header",
            field=models.CharField(
                blank=True,
                help_text="Process subsection header in principles",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="process_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_link",
            field=models.CharField(
                blank=True, help_text="Financial advisors link URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_link_text",
            field=models.CharField(
                blank=True, help_text="Financial advisors link text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_advisor_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_link",
            field=models.CharField(
                blank=True, help_text="Individual investors link URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_link_text",
            field=models.CharField(
                blank=True, help_text="Individual investors link text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_individual_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_link",
            field=models.CharField(
                blank=True, help_text="Institutions link URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_link_text",
            field=models.CharField(
                blank=True, help_text="Institutions link text", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_institution_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="serve_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for who we serve", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="since_year",
            field=models.CharField(
                blank=True, help_text="Year established or founding info", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategies_section_header",
            field=models.CharField(
                blank=True, help_text="Section header for strategies", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_description",
            field=models.TextField(
                blank=True, help_text="Description for growth strategy"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_focus",
            field=models.CharField(
                blank=True, help_text="Focus value for growth strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_link",
            field=models.CharField(
                blank=True, help_text="Link URL for growth strategy", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_link_text",
            field=models.CharField(
                blank=True, help_text="Link text for growth strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_management",
            field=models.CharField(
                blank=True,
                help_text="Management value for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_name",
            field=models.CharField(
                blank=True, help_text="Name of the first strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_ownership",
            field=models.CharField(
                blank=True,
                help_text="Ownership value for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_screening",
            field=models.CharField(
                blank=True,
                help_text="Screening value for growth strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_1_subtitle",
            field=models.CharField(
                blank=True, help_text="Subtitle for first strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_description",
            field=models.TextField(
                blank=True, help_text="Description for income strategy"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_focus",
            field=models.CharField(
                blank=True, help_text="Focus value for income strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_link",
            field=models.CharField(
                blank=True, help_text="Link URL for income strategy", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_link_text",
            field=models.CharField(
                blank=True, help_text="Link text for income strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_management",
            field=models.CharField(
                blank=True,
                help_text="Management value for income strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_name",
            field=models.CharField(
                blank=True, help_text="Name of the second strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_ownership",
            field=models.CharField(
                blank=True,
                help_text="Ownership value for income strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_screening",
            field=models.CharField(
                blank=True,
                help_text="Screening value for income strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_2_subtitle",
            field=models.CharField(
                blank=True, help_text="Subtitle for second strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_description",
            field=models.TextField(
                blank=True, help_text="Description for diversification strategy"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_focus",
            field=models.CharField(
                blank=True,
                help_text="Focus value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_link",
            field=models.CharField(
                blank=True,
                help_text="Link URL for diversification strategy",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_link_text",
            field=models.CharField(
                blank=True,
                help_text="Link text for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_management",
            field=models.CharField(
                blank=True,
                help_text="Management value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_name",
            field=models.CharField(
                blank=True, help_text="Name of the third strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_ownership",
            field=models.CharField(
                blank=True,
                help_text="Ownership value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_screening",
            field=models.CharField(
                blank=True,
                help_text="Screening value for diversification strategy",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_3_subtitle",
            field=models.CharField(
                blank=True, help_text="Subtitle for third strategy", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_label_focus",
            field=models.CharField(
                blank=True, help_text="Label for strategy focus row", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_label_management",
            field=models.CharField(
                blank=True, help_text="Label for strategy management row", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_label_ownership",
            field=models.CharField(
                blank=True, help_text="Label for strategy ownership row", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="strategy_label_screening",
            field=models.CharField(
                blank=True, help_text="Label for strategy screening row", max_length=50
            ),
        ),
    ]
