# Generated by Django 5.1.5 on 2025-07-11 21:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0026_remove_homepage_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="bluesky_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_alt_text",
            field=models.CharField(
                blank=True, help_text="Alt text for headshot image", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="headshot_image",
            field=models.URLField(blank=True, help_text="URL to headshot image"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name and pronouns", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Philosophy quote in the hero section"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link",
            field=models.CharField(
                blank=True,
                help_text="Link for the philosophy quote attribution (can be relative or absolute URL)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_quote_link_text",
            field=models.CharField(
                blank=True,
                help_text="Text for the philosophy quote link",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_title",
            field=models.CharField(
                blank=True, help_text="Professional title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="sec_info_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
    ]
