# Generated by Django 5.1.5 on 2025-07-11 22:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0027_alter_aboutpage_bluesky_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link",
            field=models.URLField(blank=True, help_text="Calendar booking link"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="calendar_link_text",
            field=models.CharField(
                blank=True, help_text="Text for calendar link", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="client_focus_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Client focus description for What I Do Now panel"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="current_role_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Current role description for What I Do Now panel"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link",
            field=models.EmailField(
                blank=True, help_text="Contact email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="email_link_text",
            field=models.CharField(
                blank=True, help_text="Text for email link", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="External roles and leadership content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="external_roles_title",
            field=models.CharField(
                blank=True, help_text="Title for external roles section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_1_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_2_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_3_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="featured_post_4_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Personal interests content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="personal_interests_title",
            field=models.CharField(
                blank=True,
                help_text="Title for personal interests section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="philosophy_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Philosophy description for What I Do Now panel"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Professional background content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="professional_background_title",
            field=models.CharField(
                blank=True,
                help_text="Title for professional background section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaker_bio_url",
            field=models.URLField(blank=True, help_text="URL to speaker bio PDF"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_contact_note",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Contact note for speaking section"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_cta_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Call-to-action text for speaking section"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_topics",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Topics covered in speaking engagements"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_content",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Speaking & writing content"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="speaking_writing_title",
            field=models.CharField(
                blank=True,
                help_text="Title for speaking & writing section",
                max_length=200,
            ),
        ),
    ]
