# Generated by Django 5.1.5 on 2025-07-11 22:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0028_remove_aboutpage_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingpage",
            name="contact_cta",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="cta_section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="enterprise_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="fee_calculation_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="fee_calculation_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_badge",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_cta_link",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_cta_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_features",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Features for individual pricing tier"
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_price",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_price_period",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="individual_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="institutional_badge",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="institutional_features",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Features for institutional pricing tier"
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="institutional_price",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="institutional_price_period",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="institutional_subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="institutional_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="minimum_investment_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="minimum_investment_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="pricing_rationale_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="pricing_rationale_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="section_header",
            field=models.CharField(
                blank=True, help_text="Main pricing section header", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="section_intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Introduction text for pricing section"
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="services_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="services_section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="show_workshop_form",
            field=models.BooleanField(
                blank=True, default=False, help_text="Show the workshop request form"
            ),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="workshop_form_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="workshop_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="workshop_nonprofit_note",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingpage",
            name="workshop_section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
