# Generated by Django 5.1.5 on 2025-07-11 22:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0029_remove_pricingpage_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_section_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="benefits_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_primary_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_primary_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_secondary_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_secondary_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="ddq_section_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="ddq_section_subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="ddq_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="offer_section_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="offer_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="process_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="services_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="advisorpage",
            name="technology_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
