# Generated by Django 5.1.5 on 2025-07-11 22:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0030_remove_advisorpage_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionalpage",
            name="benefits_section_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="benefits_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="capabilities_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_primary_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_primary_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_secondary_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_secondary_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="ddq_section_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="ddq_section_subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="ddq_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="offer_section_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="offer_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="process_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_section_intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="scale_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="institutionalpage",
            name="solutions_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
