# Generated by Django 5.1.5 on 2025-07-11 22:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0031_remove_institutional_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processpage",
            name="conduct_exclusions_subtitle",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="conduct_exclusions_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="exclusion_date",
            field=models.CharField(
                blank=True,
                help_text="Date of exclusion percentage calculation",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="exclusion_percentage",
            field=models.CharField(
                blank=True, help_text="Percentage of S&P 500 excluded", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="methodology_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="methodology_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="principles_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="principles_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="process_overview",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="product_exclusions_subtitle",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="product_exclusions_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="screening_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="screening_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step1_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step2_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step3_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="processpage",
            name="step4_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
