# Generated by Django 5.1.5 on 2025-07-11 22:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0033_remove_strategypage_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priddqpage",
            name="executive_summary",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Executive summary of ESG approach"
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="form_adv_url",
            field=models.URLField(blank=True, help_text="URL to Form ADV disclosure"),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Hero section description"
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_subtitle",
            field=models.TextField(
                blank=True,
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="hero_title",
            field=models.CharField(
                blank=True, help_text="Main headline", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="screening_policy_url",
            field=models.URLField(
                blank=True, help_text="URL to open-source screening policy"
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_additional",
            field=models.CharField(
                blank=True,
                help_text="Section subtitle for additional information",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_climate",
            field=models.CharField(
                blank=True, help_text="Section subtitle for climate", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_esg",
            field=models.CharField(
                blank=True,
                help_text="Section subtitle for ESG integration",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_executive",
            field=models.CharField(
                blank=True,
                help_text="Section subtitle for executive summary",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_reporting",
            field=models.CharField(
                blank=True, help_text="Section subtitle for reporting", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_stewardship",
            field=models.CharField(
                blank=True, help_text="Section subtitle for stewardship", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_strategy",
            field=models.CharField(
                blank=True,
                help_text="Section subtitle for strategy section",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_subtitle_transparency",
            field=models.CharField(
                blank=True,
                help_text="Section subtitle for transparency",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_additional",
            field=models.CharField(
                blank=True,
                help_text="Panel title for additional information section",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_climate",
            field=models.CharField(
                blank=True, help_text="Panel title for climate section", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_esg",
            field=models.CharField(
                blank=True,
                help_text="Panel title for ESG integration section",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_executive",
            field=models.CharField(
                blank=True,
                help_text="Panel title for executive summary section",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_overview",
            field=models.CharField(
                blank=True, help_text="Panel title for overview section", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_reporting",
            field=models.CharField(
                blank=True,
                help_text="Panel title for reporting section",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_stewardship",
            field=models.CharField(
                blank=True,
                help_text="Panel title for stewardship section",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_strategy",
            field=models.CharField(
                blank=True, help_text="Panel title for strategy section", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="section_title_transparency",
            field=models.CharField(
                blank=True,
                help_text="Panel title for transparency section",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="priddqpage",
            name="updated_at",
            field=models.CharField(
                blank=True,
                help_text="Month and year when this document was last updated",
                max_length=50,
            ),
        ),
    ]
