# Generated by Django 5.1.5 on 2025-07-11 22:36

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0035_remove_contactform_solutions_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediapage",
            name="empty_state_message",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="empty_state_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Introduction text that appears at the top of the media page",
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="press_kit_title",
            field=models.CharField(
                blank=True, help_text="Title for the press kit section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_contact_button_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_contact_button_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_contact_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_contact_show",
            field=models.BooleanField(
                blank=True, help_text="Show media contact sidebar section"
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_contact_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_interview_button_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_interview_button_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_interview_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_interview_show",
            field=models.BooleanField(
                blank=True, help_text="Show schedule interview sidebar section"
            ),
        ),
        migrations.AlterField(
            model_name="mediapage",
            name="sidebar_interview_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
