# Generated by Django 5.1.5 on 2025-07-11 22:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0036_remove_mediapage_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="reading_time",
            field=models.IntegerField(
                blank=True, help_text="Estimated reading time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="alternative_contact_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="contact_email",
            field=models.EmailField(
                blank=True, help_text="Contact email for consultations", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="disclaimer_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="disclaimer_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="expectations_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_subtitle",
            field=models.TextField(
                blank=True,
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="hero_title",
            field=models.CharField(
                blank=True, help_text="Main headline", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="schedule_intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="consultationpage",
            name="schedule_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_note",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Note about exclusions"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="exclusions_section_title",
            field=models.CharField(
                blank=True, help_text="Title for exclusions section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="github_criteria_url",
            field=models.URLField(
                blank=True, help_text="URL to GitHub screening policy"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_subtitle",
            field=models.TextField(
                blank=True,
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="hero_title",
            field=models.CharField(
                blank=True, help_text="Main headline", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_benefits",
            field=models.TextField(
                blank=True, help_text="Benefits of transparency, one per line"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Description of transparency approach"
            ),
        ),
        migrations.AlterField(
            model_name="criteriapage",
            name="transparency_section_title",
            field=models.CharField(
                blank=True, help_text="Title for transparency section", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaentry",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="encyclopediaindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="empty_state_button_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="empty_state_button_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="empty_state_message",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="empty_state_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="description_section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="download_section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_subtitle",
            field=models.TextField(
                blank=True,
                help_text="Subtitle text below the main headline",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="hero_title",
            field=models.CharField(
                blank=True, help_text="Main headline", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="newsletter_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="newsletter_section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="guidepage",
            name="resources_section_header",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="form_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_message",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="onboardingpage",
            name="thank_you_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="featured_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="researchpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="comparison_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="cta_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="cta_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="resources_section_description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="resources_section_subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategylistpage",
            name="resources_section_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
