# Generated by Django 5.1.5 on 2025-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0037_remove_model_defaults_for_cms_editability"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategypage",
            name="latest_month_benchmark",
            field=models.CharField(
                blank=True,
                help_text="Enter latest month benchmark return (e.g., '4.64%')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="strategypage",
            name="latest_month_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the latest monthly data (e.g., June 30, 2025)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategypage",
            name="latest_month_return",
            field=models.CharField(
                blank=True,
                help_text="Enter latest month return (e.g., '5.51%') - will auto-update all calculations",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="strategypage",
            name="monthly_returns",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Historical monthly returns data {year: {month: {strategy: %, benchmark: %}}}",
            ),
        ),
        migrations.AddField(
            model_name="strategypage",
            name="performance_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="When performance data was last updated",
                null=True,
            ),
        ),
    ]
