# Generated by Django 5.1.5 on 2025-07-13 00:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0038_add_monthly_performance_fields"),
        ("wagtailcore", "0096_add_newsletter_accessibility_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessibilityPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro_text", wagtail.fields.RichTextField(blank=True)),
                ("standards_text", wagtail.fields.RichTextField(blank=True)),
                ("features_text", wagtail.fields.RichTextField(blank=True)),
                ("feedback_text", wagtail.fields.RichTextField(blank=True)),
                ("technical_text", wagtail.fields.RichTextField(blank=True)),
                ("limitations_text", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Accessibility Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsletterPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro_text", wagtail.fields.RichTextField(blank=True)),
                ("benefits_title", models.CharField(blank=True, max_length=200)),
                ("benefits_text", wagtail.fields.RichTextField(blank=True)),
                ("privacy_text", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Newsletter Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
