# Generated by Django 5.1.5 on 2025-07-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_site", "0039_add_newsletter_accessibility_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="external_reference",
            field=models.CharField(
                blank=True,
                help_text="External submission ID for tracking secure API submissions",
                max_length=255,
                null=True,
            ),
        ),
    ]
