# Generated by Django 5.1.5 on 2025-08-23 05:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0040_add_external_reference_to_support_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("image", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                },
                help_text="Add content blocks to your blog post",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
