#!/bin/bash
# Test runner script for public_site tests
# To be used once public_site is added to INSTALLED_APPS

echo "=================================================="
echo "Public Site Test Runner"
echo "=================================================="
echo ""
echo "NOTE: This test suite requires:"
echo "1. public_site to be in INSTALLED_APPS"
echo "2. Wagtail apps to be properly configured"
echo "3. Database migrations to be run"
echo ""
echo "To add public_site to your Django project:"
echo "1. Add 'public_site' to INSTALLED_APPS in settings.py"
echo "2. Add required Wagtail apps if not present:"
echo "   - 'wagtail'"
echo "   - 'wagtail.admin'"
echo "   - 'wagtail.documents'"
echo "   - 'wagtail.images'"
echo "   - 'wagtail.search'"
echo "   - 'wagtail.sites'"
echo "   - 'wagtail.users'"
echo "   - 'wagtail.snippets'"
echo "   - 'modelcluster'"
echo "   - 'taggit'"
echo "3. Run migrations: python manage.py migrate"
echo ""
echo "Once configured, run tests with:"
echo "  python manage.py test public_site.tests -v 2"
echo ""
echo "Or run specific test modules:"
echo "  python manage.py test public_site.tests.test_quick -v 2"
echo "  python manage.py test public_site.tests.models -v 2"
echo "  python manage.py test public_site.tests.views -v 2"
echo "  python manage.py test public_site.tests.forms -v 2"
echo "  python manage.py test public_site.tests.integration -v 2"
echo ""
echo "For coverage report:"
echo "  coverage run --source='public_site' manage.py test public_site.tests"
echo "  coverage report"
echo "  coverage html"
echo ""