name: CSS Conflict Prevention

on:
  push:
    branches: [main, develop]
    paths:
      - "static/css/**"
      - "templates/**"
  pull_request:
    branches: [main]
    paths:
      - "static/css/**"
      - "templates/**"

jobs:
  css-conflict-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run CSS conflict tests
        run: |
          python -m pytest tests/test_css_conflicts.py -v --tb=short

      - name: Check CSS baseline
        run: |
          # Create baseline if it doesn't exist
          if [ ! -f css_baseline.json ]; then
            python css_monitoring.py --create-baseline
          fi

          # Check for regressions
          python css_monitoring.py --check

      - name: Generate CSS report
        if: failure()
        run: |
          python css_monitoring.py --report > css_report.txt
          echo "## CSS Conflict Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat css_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload CSS report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: css-conflict-report
          path: css_report.txt

  template-consistency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for deprecated CSS classes
        run: |
          echo "🔍 Checking for deprecated CSS classes in templates..."

          # Check for old Bootstrap/form classes
          if grep -r "form-control\|form-input\|btn-primary\|btn-secondary" templates/ --include="*.html"; then
            echo "❌ Found deprecated CSS classes!"
            echo "Please replace with Garden UI classes:"
            echo "  form-control → garden-input"
            echo "  btn-primary → garden-action primary"
            echo "  btn-secondary → garden-action secondary"
            exit 1
          fi

          echo "✅ No deprecated CSS classes found"

      - name: Check Garden UI usage
        run: |
          echo "🔍 Checking Garden UI adoption..."

          # Count Garden UI usage
          garden_usage=$(grep -r "garden-" templates/ --include="*.html" | wc -l || echo "0")
          echo "Garden UI classes found: $garden_usage"

          if [ "$garden_usage" -lt 10 ]; then
            echo "⚠️  Low Garden UI adoption detected"
            echo "Consider migrating more components to Garden UI"
          else
            echo "✅ Good Garden UI adoption"
          fi
